### ISSUE TITLE
Problems with Switch sensors

### ISSUE THREAD

**Issue by Gaff** [StyraHem/ShellyForHASS#280] opened 2020-04-27 15:01 UTC
I'm trying to configure my switches in detached mode. I'm using 0.108.9 and 0.17.1 of the pluigin. I've changed the config like so:

```yaml
shelly:
  devices:
    - id: "259B4D"
      sensors: 
         - power
         - switch
```

I've noticed a couple of issues:

1. ALL my shelly devices now appear as switches, not just this one!

2. When I toggle the shelly from hass (the original switch, not the new sensor) I get an error:

```
2020-04-27 15:51:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2933400240] 'switch.shelly_shsw_1_259b4d'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1232, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1255, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 378, in entity_service_call
    entity_ids.remove(entity.entity_id)
KeyError: 'switch.shelly_shsw_1_259b4d'
```

How should I get this to work?

**Comment by chemelli74** [comment] 2020-05-03 12:13
Please update to 0.1.8b2 and report back.

Simone

**Comment by chemelli74** [comment] 2020-05-17 09:13
Hi all, just to inform that after 3 weeks of inactivity on thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-05-24 23:16
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-05-24 23:16 UTC
Labels: question, waiting for feedback
