### ISSUE TITLE
Shelly 2.0 Roller Position Bug

### ISSUE THREAD

**Issue by niklasfink** [StyraHem/ShellyForHASS#199] opened 2020-02-21 21:02 UTC
Hi, the positioning for my Shelly 2.0 roller mode doesn't work properly.
The positions reading always jumps back to the last position and stays there, even after the shutter finished the movement.

I made a quick Video here where you can see the issue. You can also see when the shutter is moving, when one of the arrow buttons on the top right are greyed out.
https://imgur.com/a/smTU07S

HA V0.105.5
ShellyForHASS V0.1.6

**Comment by hakana** [comment] 2020-02-21 23:12
What is the value on position if you go url /status?

**Comment by niklasfink** [comment] 2020-02-22 08:18
/status shows the new (correct) value. `rollers.current_pos: [correctValue]`

**Comment by niklasfink** [comment] 2020-02-22 08:20
I can see that after around 10 seconds, the HA UI gets updated to the correct value. However, the /status already updates right after the movement finishes.

**Comment by gogui63** [comment] 2020-03-03 10:18
Same issue with Shelly 2.5 on my roller.

Fully open but position is 50.
Position works great in Shelly app.

**Comment by chemelli74** [comment] 2020-03-14 09:47
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-03-27 14:55
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-03-27 14:55 UTC
Labels: question, waiting for feedback
