### ISSUE TITLE
[FR] allow power_decimals also as device config

### ISSUE THREAD

**Issue by vistalba** [StyraHem/ShellyForHASS#203] opened 2020-02-25 08:38 UTC
Feature Request:

Also allow use of `power_decimals` on device config.

I've different energy meters. One of them has a very constant load. So I use `power_decimals: 1` to get updates more often (maybe 2-4 times in 5 minutes).

The other energy meter has a very vaiable load. Here I want to use `power_decimals: 0` so that the values doesn't change so often and save some space because my DB is growing huge atm.

**Comment by hakana** [comment] 2020-03-09 23:15
Fixed in 0.1.7.b2, will be released in some days

**Comment by chemelli74** [comment] 2020-03-14 09:00
Please update to latest beta (0.1.7.b2) and recheck.

Simone

**Comment by chemelli74** [comment] 2020-03-22 11:15
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Closed** 2020-03-22 11:17 UTC
Labels: enhancement, fixed, waiting for feedback
