### ISSUE TITLE
Component not working

### ISSUE THREAD

**Issue by elmgrenen** [StyraHem/ShellyForHASS#97] opened 2019-11-13 13:51 UTC
I'm having issues adding this component to HA, I've tried with HACS and without it.

No devices are showing at all, I have two plugs and one Shelly bulb. I managed to get it to work at a friends house, he had one plug and one bulb and I only got the plug to work, not the bulb.

What am I doing wrong? I've added shelly: to my config.yaml and all files are in custom_components/shelly

**Comment by Puntoboy** [comment] 2019-11-18 17:14
Same issue here. The entity is listed, but nothing under Devices.

**Comment by hakana** [comment] 2019-11-19 22:47
Probably the firewall that not allow UDP on port 5683 or a Switch. Can you see any errors in log from Shelly?

**Comment by Puntoboy** [comment] 2019-11-20 10:21
OK I can see the Shelly devices on the Overview page and listed under entity_id but not under devices. I can control them from the overview page.

How do I create the automations?

**Comment by joriskalz** [comment] 2019-11-25 20:11
Having the same issue, entities are available but nothing under devices. No related error messages in the log.  No automations possible.

**Comment by chemelli74** [comment] 2020-01-21 10:48
@Puntoboy, @joriskalz , can you please retest with 0.1.6b6 ? Please update firmware to latest v1.5.7 as well.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-01-30 15:03
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-02-11 15:02
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-02-11 15:02 UTC
Labels: question
