### ISSUE TITLE
Unable update device status

### ISSUE THREAD

**Issue by antoweb** [StyraHem/ShellyForHASS#361] opened 2020-07-31 16:58 UTC
## Environment

- ShellyForHASS release with the issue:  0.1.9
- Last working ShellyForHASS release (if known): 0.1.8
- Home Assistant Core release with the issue: 0.113.2
- Operating environment (Home Assistant/Supervised/Docker/venv): Hassos/Hassio

## Describe the bug
Error in log

2020-07-31 18:56:58 ERROR (Poll) [pyShelly] Error update loop, , Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 270, in _update_loop
    block.check_available()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 128, in check_available
    dev.raise_updated()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/device.py", line 125, in raise_updated
    callback(self)
  File "/config/custom_components/shelly/device.py", line 53, in _updated
    self.schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 416, in schedule_update_ha_state
    assert self.hass is not None
AssertionError
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 270, in _update_loop
    block.check_available()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 128, in check_available
    dev.raise_updated()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/device.py", line 125, in raise_updated
    callback(self)
  File "/config/custom_components/shelly/device.py", line 53, in _updated
    self.schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 416, in schedule_update_ha_state
    assert self.hass is not None
AssertionError

## Traceback/Error logs

```txt

```

**Comment by chemelli74** [comment] 2020-08-01 12:39
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 416, in schedule_update_ha_state
> assert self.hass is not None
> AssertionError

Duplicate of #341, closing.

Simone

**Closed by chemelli74** 2020-08-01 12:39 UTC
