### ISSUE TITLE
Extra total consumption attribute added.

### ISSUE THREAD

**Issue by GoNzCiD** [StyraHem/ShellyForHASS#196] opened 2020-02-21 10:33 UTC
Hi, I've trying latest [0.1.6 version](https://github.com/StyraHem/ShellyForHASS/releases/tag/0.1.6) and it's amazing (thanks) to use attributes collection in order to not over use recorder, like described in RN `Default attributes have changed to decrease database activity, can be configured by attributes setting`

But I have notice that if I only want to add `has_firmware_upgrade` and `consumption` like:
```yaml
attributes:
  - has_firmware_update
  - consumption
```

If I enable additional information (`additional_information: true`), it adds an extra total_consumption attribute to the entity (light) that increase continously when device is on (and something is plugged-in, obviously). So recorder is going to write continously while total_consumption increase. 

Exits any possibility to exlude the total consumption attribute and only add it when it's declared on `attributes` configuration?

Thanks

**Comment by chemelli74** [comment] 2020-03-14 08:51
Please update to latest beta (0.1.7.b2) and recheck.

Simone

**Comment by chemelli74** [comment] 2020-03-18 22:24
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by GoNzCiD** [comment] 2020-03-19 07:49
b2 changes are included in b3?

**Comment by GoNzCiD** [comment] 2020-03-19 08:04
Hi,

I've tested 0.1.7.b2 & 0.1.7.b3 with same result, unfortunatelly.
![imagen](https://user-images.githubusercontent.com/12912439/77044855-74a79b00-69c0-11ea-8acc-757a3beb087f.png)

The configuration is like this:
```
additional_information: true
power_decimals: 2
scan_interval: 5
attributes:
  - has_firmware_update
  - consumption
```

**Comment by hakana** [comment] 2020-03-19 09:59
consumption will add both current_consumpton and total_consumption. Use current_consumption if you just need that attribute.

**Comment by GoNzCiD** [comment] 2020-03-19 10:45
> 
> 
> consumption will add both current_consumpton and total_consumption. Use current_consumption if you just need that attribute.

Yes, I know to use only the attribute I need. But the 'problem' is: "If `total_consumption` is added, then the entity is constantly updated and recorder persist data into database. 
If the idea is to **decrease database activity**, adding `total_consumption` by default don't help.

Thanks

**Comment by hakana** [comment] 2020-03-24 16:31
Yes, but total_consumption is not added by default.

It is added because you use consumption attributes that include both total and current.

**Comment by chemelli74** [comment] 2020-03-24 16:49
Closing issue

**Closed by chemelli74** 2020-03-24 16:49 UTC
Labels: enhancement, waiting for feedback
