### ISSUE TITLE
Shelly disconnected on hassio 103.3

### ISSUE THREAD

**Issue by wifi75** [StyraHem/ShellyForHASS#106] opened 2019-11-30 21:50 UTC
Maybe it is the last firmware, but all entities are . disconnected, what can I do?

**Comment by hakana** [comment] 2019-11-30 23:40
Did it work before?

**Comment by wifi75** [comment] 2019-12-01 11:49
Yes... I think after last firmware update

**Comment by wifi75** [comment] 2019-12-01 18:58
I confirm the problem it is the last update firmware 1.5.6 ! Because I tryed to downgrade hassio to 102.1, and shelly not found!

**Comment by wifi75** [comment] 2019-12-02 07:11
I'have update component to beta versione 0.1.3,now I see agian all entities but but they respond to the command slowly

**Comment by chemelli74** [comment] 2020-01-21 10:51
@wifi75 , can you please retest with 0.1.6b6 ? Please update firmware to latest v1.5.7 as well.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-01-30 15:05
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-02-11 15:02
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-02-11 15:02 UTC
Labels: question
