### ISSUE TITLE
Too many (Thread-148) [pyShelly] Get status from XXXXX Shelly 2.5

### ISSUE THREAD

**Issue by itayraviv** [StyraHem/ShellyForHASS#132] opened 2020-01-01 07:42 UTC
Hi,

After installing and integrating to HA, the 4 x Shelly 2.5 were added to HA and are working.
but I see many messages in HA log which eventually (after a night or few hours) causing the home assistant not work anymore, those are the messages:

2020-01-01 09:34:10 INFO (Thread-162) [pyShelly] Get status from 7453A2 Shelly 2.5
2020-01-01 09:34:10 INFO (Thread-163) [pyShelly] Get status from 7448DA Shelly 2.5
2020-01-01 09:34:10 INFO (Thread-164) [pyShelly] Get status from 740995 Shelly 2.5
2020-01-01 09:35:10 INFO (Thread-165) [pyShelly] Get status from 7458B0 Shelly 2.5
2020-01-01 09:35:10 INFO (Thread-166) [pyShelly] Get status from 7453A2 Shelly 2.5
2020-01-01 09:35:10 INFO (Thread-167) [pyShelly] Get status from 7448DA Shelly 2.5
2020-01-01 09:35:10 INFO (Thread-168) [pyShelly] Get status from 740995 Shelly 2.5
2020-01-01 09:36:10 INFO (Thread-169) [pyShelly] Get status from 7458B0 Shelly 2.5
2020-01-01 09:36:10 INFO (Thread-170) [pyShelly] Get status from 7453A2 Shelly 2.5
2020-01-01 09:36:10 INFO (Thread-171) [pyShelly] Get status from 7448DA Shelly 2.5
2020-01-01 09:36:10 INFO (Thread-172) [pyShelly] Get status from 740995 Shelly 2.5
2020-01-01 09:37:10 INFO (Thread-173) [pyShelly] Get status from 7458B0 Shelly 2.5
2020-01-01 09:37:10 INFO (Thread-174) [pyShelly] Get status from 7453A2 Shelly 2.5
2020-01-01 09:37:10 INFO (Thread-175) [pyShelly] Get status from 7448DA Shelly 2.5
2020-01-01 09:37:10 INFO (Thread-176) [pyShelly] Get status from 740995 Shelly 2.5
2020-01-01 09:38:10 INFO (Thread-177) [pyShelly] Get status from 7458B0 Shelly 2.5
2020-01-01 09:38:10 INFO (Thread-178) [pyShelly] Get status from 7453A2 Shelly 2.5
2020-01-01 09:38:10 INFO (Thread-179) [pyShelly] Get status from 7448DA Shelly 2.5
2020-01-01 09:38:10 INFO (Thread-180) [pyShelly] Get status from 740995 Shelly 2.5
2020-01-01 09:39:11 INFO (Thread-181) [pyShelly] Get status from 7458B0 Shelly 2.5
2020-01-01 09:39:11 INFO (Thread-182) [pyShelly] Get status from 7453A2 Shelly 2.5
2020-01-01 09:39:11 INFO (Thread-183) [pyShelly] Get status from 7448DA Shelly 2.5
2020-01-01 09:39:11 INFO (Thread-184) [pyShelly] Get status from 740995 Shelly 2.5

Anyone saw those before? or have an idea why it makes the HA stop working?
* Removing the shelly integration from HACS solves it obviously.
* All shelly modules are not updated to the latest module - maybe that's the issue?

Thanks to anyone who can help..

**Comment by itayraviv** [comment] 2020-01-01 07:49
trying to restart the home assistant docker shows the following errors, maybe it can help?

2020-01-01 09:45:16 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
2020-01-01 09:45:16 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 275, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 394, in _async_write_ha_state
    self.entity_id, state, attr, self.force_update, self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 988, in async_set
    state = State(entity_id, new_state, attributes, last_changed, None, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 725, in __init__
    ).format(entity_id)
homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: .shelly_shsw_25_7448da. Format should be <domain>.<object_id>
2020-01-01 09:45:16 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 275, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 394, in _async_write_ha_state
    self.entity_id, state, attr, self.force_update, self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 988, in async_set
    state = State(entity_id, new_state, attributes, last_changed, None, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 725, in __init__
    ).format(entity_id)
homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: .shelly_shsw_25_740995. Format should be <domain>.<object_id>
2020-01-01 09:45:41 INFO (Thread-17) [pyShelly] Get status from 7458B0 Shelly 2.5
2020-01-01 09:45:41 INFO (Thread-18) [pyShelly] Get status from 7453A2 Shelly 2.5
2020-01-01 09:45:42 INFO (Thread-19) [pyShelly] Get status from 740995 Shelly 2.5
2020-01-01 09:45:42 INFO (Thread-20) [pyShelly] Get status from 7448DA Shelly 2.5

**Comment by rufik** [comment] 2020-01-01 10:19
Same here:
```
2019-12-31 12:27:58 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 286, in async_update_ha_state,
    self._async_write_ha_state(),
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 405, in _async_write_ha_state,
    self.entity_id, state, attr, self.force_update, self._context,
  File "/usr/src/homeassistant/homeassistant/core.py", line 987, in async_set,
    state = State(entity_id, new_state, attributes, last_changed, None, context),
  File "/usr/src/homeassistant/homeassistant/core.py", line 724, in __init__,
    ).format(entity_id),
homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: .shelly_shsw_1_93a6b5. Format should be <domain>.<object_id>
```
and then:
```
2019-12-31 12:28:42 INFO (Poll) [pyShelly] Add device from IP, 93A6B5, SHSW-1, 192.168.66.31
```

**Comment by rubenas** [comment] 2020-01-01 16:20
Same for me. It happens once or twice a week but usually I don't get any error reports. It's weird...

**Comment by itayraviv** [comment] 2020-01-01 16:59
messages stops when i remove the Shelly Integration from HACS and "shelly:" from configuration.yaml
I remember I had this working but maybe from a specific update it was broken.. 
any suggestions?

**Comment by hakana** [comment] 2020-01-01 23:06
Can you try to keep it installed and just remove shelly: from config

**Comment by itayraviv** [comment] 2020-01-05 06:56
@hakana -  no issue when the Shelly HACS integration is installed and the "shelly:" section in configuration.yaml is disabled.

**Comment by hakana** [comment] 2020-01-14 22:48
Fixed in 0.1.6.b4

**Comment by Misiu** [comment] 2020-01-16 09:01
@itayraviv please check with the latest release and close this issue if everything works. Thanks 🙂

**Comment by chemelli74** [comment] 2020-01-22 12:45
@rufik, @ itayraviv, can you please update to a current HA version ( > 0.10.4.0 ) and to latest 0.1.6b7 version of this plugin are retest ?

Thank you,

Simone

**Comment by itayraviv** [comment] 2020-02-03 23:10
updated to latest HA version and latest plugin.
current state is that i still have many of these messages in the HA log:
2020-02-04 01:05:16 INFO (Thread-420) [pyShelly] Get status from 740995 Shelly 2.5
2020-02-04 01:05:17 INFO (Thread-422) [pyShelly] Get status from 7453A2 Shelly 2.5
2020-02-04 01:06:13 INFO (Thread-435) [pyShelly] Get status from 7458B0 Shelly 2.5
2020-02-04 01:06:13 INFO (Thread-436) [pyShelly] Get status from 7448DA Shelly 2.5
2020-02-04 01:06:17 INFO (Thread-438) [pyShelly] Get status from 740995 Shelly 2.5
2020-02-04 01:06:18 INFO (Thread-439) [pyShelly] Get status from 7453A2 Shelly 2.5

under configuratio.yaml i have:
shelly:
#  discovery: true  # Add all devices
#  version: true    # Add version sensor
  username: !secret shelly_username
  password: !secret shelly_password

as for now (~ 1 hour since upgrade) looks like it is ok, ill wait a few more hours to see if it keeps on working.
anyway I don't understand why I get these too many logs even that it's INFO.. any ideas?

**Comment by hakana** [comment] 2020-02-03 23:14
You can turn off them by change the logger settings in config.yaml

```yaml
logger:
  default: error
```
or

```yaml
logger:
  logs:
    pyShelly: error
```

**Comment by rmarkiewicz** [comment] 2020-02-04 07:41
> You can turn off them by change the logger settings in config.yaml
> ```yaml
> logger:
>   logs:
>     pyShelly: error
> ```

I would suggest change this message to `debug` level to not flood log file.
And as workaround it's better to set `warn` level for now, so pyShelly errors will be still visible.

**Comment by itayraviv** [comment] 2020-02-04 13:22
I just updated via HACS to the build released 2 hours ago and it broke HA, its not starting, log messages are full of:
2020-02-04 15:19:51 INFO (CoAP) [pyShelly] Update id:7453A2 state:True stateValue:None values:None info_values:{'current_consumption': 0.0}
2020-02-04 15:19:51 INFO (CoAP) [pyShelly] Update id:7453A2-1 state:0.0 stateValue:None values:None info_values:None
2020-02-04 15:19:51 INFO (CoAP) [pyShelly] Update id:7453A2-1 state:False stateValue:None values:None info_values:None
2020-02-04 15:19:51 INFO (CoAP) [pyShelly] Update id:7453A2-2 state:False stateValue:None values:None info_values:None
2020-02-04 15:19:58 INFO (CoAP) [pyShelly] Update id:740995 state:True stateValue:None values:None info_values:{'current_consumption': 0.0}
2020-02-04 15:19:58 INFO (CoAP) [pyShelly] Update id:740995-1 state:0.0 stateValue:None values:None info_values:None
2020-02-04 15:19:58 INFO (CoAP) [pyShelly] Update id:740995-1 state:False stateValue:None values:None info_values:None
2020-02-04 15:19:58 INFO (CoAP) [pyShelly] Update id:740995-2 state:False stateValue:None values:None info_values:None
2020-02-04 15:20:02 INFO (CoAP) [pyShelly] Update id:7448DA state:True stateValue:None values:None info_values:{'current_consumption': 0.0}
2020-02-04 15:20:02 INFO (CoAP) [pyShelly] Update id:7448DA-1 state:0.0 stateValue:None values:None info_values:None
2020-02-04 15:20:02 INFO (CoAP) [pyShelly] Update id:7448DA-1 state:False stateValue:None values:None info_values:None
2020-02-04 15:20:02 INFO (CoAP) [pyShelly] Update id:7448DA-2 state:False stateValue:None values:None info_values:None
2020-02-04 15:20:06 INFO (CoAP) [pyShelly] Update id:7453A2 state:True stateValue:None values:None info_values:{'current_consumption': 0.0}
2020-02-04 15:20:06 INFO (CoAP) [pyShelly] Update id:7453A2-1 state:0.0 stateValue:None values:None info_values:None
2020-02-04 15:20:06 INFO (CoAP) [pyShelly] Update id:7453A2-1 state:False stateValue:None values:None info_values:None
2020-02-04 15:20:06 INFO (CoAP) [pyShelly] Update id:7453A2-2 state:False stateValue:None values:None info_values:None
2020-02-04 15:20:13 INFO (CoAP) [pyShelly] Update id:740995 state:True stateValue:None values:None info_values:{'current_consumption': 0.0
2020-02-04 15:20:13 INFO (CoAP) [pyShelly] Update id:740995-1 state:0.0 stateValue:None values:None info_values:None
2020-02-04 15:20:13 INFO (CoAP) [pyShelly] Update id:740995-1 state:False stateValue:None values:None info_values:None
2020-02-04 15:20:13 INFO (CoAP) [pyShelly] Update id:740995-2 state:False stateValue:None values:None info_values:None
2020-02-04 15:20:17 INFO (CoAP) [pyShelly] Update id:7448DA state:True stateValue:None values:None info_values:{'current_consumption': 0.0}
2020-02-04 15:20:17 INFO (CoAP) [pyShelly] Update id:7448DA-1 state:0.0 stateValue:None values:None info_values:None
2020-02-04 15:20:17 INFO (CoAP) [pyShelly] Update id:7448DA-1 state:False stateValue:None values:None info_values:None
2020-02-04 15:20:17 INFO (CoAP) [pyShelly] Update id:7448DA-2 state:False stateValue:None values:None info_values:None
2020-02-04 15:20:21 INFO (CoAP) [pyShelly] Update id:7453A2 state:True stateValue:None values:None info_values:{'current_consumption': 0.0}
2020-02-04 15:20:21 INFO (CoAP) [pyShelly] Update id:7453A2-1 state:0.0 stateValue:None values:None info_values:None
2020-02-04 15:20:21 INFO (CoAP) [pyShelly] Update id:7453A2-1 state:False stateValue:None values:None info_values:None
2020-02-04 15:20:21 INFO (CoAP) [pyShelly] Update id:7453A2-2 state:False stateValue:None values:None info_values:None

any ideas?

**Comment by itayraviv** [comment] 2020-02-04 13:47
restarting HA and/or the entire host machine not helping, HA can't start, something with this update broke HA or HACS or both..

**Comment by hakana** [comment] 2020-02-04 14:31
No, take a backup of config.yaml and start removing things from config.yaml until it starts working.

**Comment by chemelli74** [comment] 2020-02-05 23:24
@itayraviv, did you manage to have a working HA ?
If so, please set logger to your preference and report back.

**Comment by itayraviv** [comment] 2020-02-06 09:27
I managed to have HA up again but I keep getting TONS of these messages, where can I set the log level? under HA configuration.yaml file? I tried under shelly section like this and I HA says invalid config: 

shelly:
  discovery: true  # Add all devices
#  version: true    # Add version sensor
  username: !secret shelly_username
  password: !secret shelly_password
  logger:
    logs:
      pyShelly: warn

**Comment by hakana** [comment] 2020-02-06 09:39
The logger should not be under shelly, move it to the root level.

https://www.home-assistant.io/integrations/logger/

**Comment by itayraviv** [comment] 2020-02-06 10:25
thanks for clarifying ..
ok did it, now what? wait and see if an error pops?

**Comment by chemelli74** [comment] 2020-02-09 14:25
> thanks for clarifying ..
> ok did it, now what? wait and see if an error pops?

Log should not report any "INFO" massage any more if correctly configured.

Simone

**Comment by chemelli74** [comment] 2020-02-19 22:51
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-03-02 09:56
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-03-02 09:56 UTC
Labels: fixed, waiting for feedback
