### ISSUE TITLE
A period of Total consumption

### ISSUE THREAD

**Issue by tiberius25** [StyraHem/ShellyForHASS#200] opened 2020-02-22 10:24 UTC
Hi,
Tnx a lot for your plugin.
My question is: for what period is the data displayed in the sensor "Total consumption"? Because this data does not correspond to what I see in my Shelly cloud neither in 24 hours, nor in a week.  And I can’t catch the moment when this sensor is reset.
![Annotation 2020-02-22 122200](https://user-images.githubusercontent.com/54347519/75090696-2d1f2200-556e-11ea-9a6a-6eb784a5d999.png)
![Annotation 2020-02-22 122217](https://user-images.githubusercontent.com/54347519/75090697-2db7b880-556e-11ea-9622-9e17c9a2afe6.png)

**Comment by NateLogan** [comment] 2020-02-24 22:53
Same issue here. I think that the Shelly for Hass is dividing the total consumption by 60... Also Shelly EM doesn't reset the total consumption counter.

**Comment by tiberius25** [comment] 2020-02-25 05:27
> Same issue here. I think that the Shelly for Hass is dividing the total consumption by 60... Also Shelly EM doesn't reset the total consumption counter.

What 60?.. And i mean resetting the counter of shelly plugin's sensor.

**Comment by vistalba** [comment] 2020-02-25 08:30
The value is since last reboot of shelly.

**Comment by chemelli74** [comment] 2020-02-25 12:11
If you want to compare values you need to use **utility_meter** in HA.
Shelly's firmware has a total increesing value since last reboot.

Simone

**Comment by NateLogan** [comment] 2020-02-25 13:50
> If you want to compare values you need to use **utility_meter** in HA.
> Shelly's firmware has a total increesing value since last reboot.
> 
> Simone

Yeah, I have configured an utility meter for heatpump (measured by Shelly EM) and right now today's consumption is 5439 Wh (data from Shelly cloud), but HA utility meter shows only 91 Wh. And 91x60 is 5460...

Although it might be a bug on Shelly side. 

Also I'm pretty sure that Shelly EM and 3EM are only Shelly devices, which keep total consumption between restarts.

**Comment by chemelli74** [comment] 2020-02-25 14:42
I bet we can close this issue, right ?

Simone

**Comment by rgutialo** [comment] 2020-03-03 12:42
Hi, I have the same problem as @NateLogan . I see that my total comsuption in shelly attribute is much less than the real one. How did you fix it?.

Thanks.

**Comment by chemelli74** [comment] 2020-03-03 18:01
> Hi, I have the same problem as @NateLogan . I see that my total comsuption in shelly attribute is much less than the real one. How did you fix it?.
> 
> Thanks.

You need to wait for 1.7b1

Simone

**Comment by chemelli74** [comment] 2020-03-16 13:27
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by tiberius25** [comment] 2020-03-16 13:32
Hi, there is no upgrade to 0.1.7b1 in HACS.

**Comment by chemelli74** [comment] 2020-03-16 13:35
> Hi, there is no upgrade to 0.1.7b1 in HACS.

https://github.com/StyraHem/ShellyForHASS/wiki/FAQ5:-Enable-beta-in-HACS

Simone

**Closed** 2020-03-16 13:37 UTC
Labels: bug, fixed, waiting for feedback
