### ISSUE TITLE
Energy attribute

### ISSUE THREAD

**Issue by Limych** [StyraHem/ShellyForHASS#61] opened 2019-08-28 01:19 UTC
Please add `energy` attribute for devices. It will be better in kWh.

**Comment by catalinbordan** [comment] 2019-08-28 12:08
Yes it will be nice

**Comment by tomlut** [comment] 2019-10-05 04:44
+1 for this.

**Comment by zsbobbob** [comment] 2019-10-27 19:07
yes, this features would be appreciated

**Comment by fverschure** [comment] 2019-11-30 20:44
waiting for this feature as well. would be a great addition as in mqtt you have kwh values, but this disables cloud...

**Comment by hakana** [comment] 2019-11-30 23:38
Yes, we will add this soon

**Comment by chemelli74** [comment] 2020-01-22 07:04
@Limych I think you are refering to "consumption" value as there is no attribute "energy".
Please check at http://x.x.x.x/status.

Requested attribute is pulled since a while.

Simone

**Comment by fverschure** [comment] 2020-01-23 13:06
Hi Simone, 
Something else in meant in this request then what you are referring to I guess:

The request is to add an energy attribute to show the consumtion of a device in **KwH.**
This could be implemented in the shelly component, but also leveraging the consuption attribute and  a calculation. In order to do so you would need to know the resolution of the consumption object to allow this to convert to kWh.

**Comment by chemelli74** [comment] 2020-01-23 13:33
Hi,

please check under HA->developer tools->states->sensor.shelly_shsw_25_xxxxxx_1_consumption:
you will find "unit_of_measurement: W".

I don't see any other value, so I bet you must to some maths in HA to get what you want. But I may be wrong.

Simone

**Comment by fverschure** [comment] 2020-01-24 20:08
Hi Simone, 
As mentioned earlier there is a difference in parameters send by MQTT and available via Shelly4Hass:
See below which are available in MQTT:
shellies/<model>-<deviceid>/relay/0 to report status: on, off or overpower
shellies/<model>-<deviceid>/relay/0/power to report instantaneous power consumption rate in Watts
shellies/<model>-<deviceid>/relay/0/**energy** to report amount of energy consumed in **Watt-minute**
shellies/<model>-<deviceid>/relay/0/command accepts on, off or toggle and applies accordingly
Shelly PlugS adds:
shellies/shellyplug-s-<deviceid>/temperature reports internal device temperature in °C
shellies/shellyplug-s-<deviceid>/overtemperature reports 1 when device has overheated, normally 0

The energy attribute is not available in shelly4hass and as mentioned not very easy to calculate if you do not know the resolution of the power sensor. Is there also a energy attribute provided in the COAP mesesage like in MQTT?

**Comment by hakana** [comment] 2020-01-24 21:55
No there is no total in CoAP message. I will add total from /status later.

**Comment by chemelli74** [comment] 2020-01-26 19:17
@Limych, @fverschure, attribute "total_consumption" was added to 0.1.6b9. 
We are still trying to fix the math ( see #168 ) but it's there.

Can you test latest beta and report back ?

Simone

**Comment by zsbobbob** [comment] 2020-01-26 20:46
Thanks for updating! Tested with Shelly Plug S, looks good. Is it possible to use kwh for the sensor instead of wh?

**Comment by chemelli74** [comment] 2020-01-26 21:45
As you confirmed attribute is now there, I'll close this issue.
Please follow issue #168.

Thank you,

Simone

**Closed by chemelli74** 2020-01-26 21:45 UTC
Labels: enhancement
