### ISSUE TITLE
<pyShelly.mdns.MDns object at 0x0408ABF8>

### ISSUE THREAD

**Issue by Bestchampy** [StyraHem/ShellyForHASS#326] opened 2020-06-16 17:11 UTC
Hello,

I have this futur warning by HASS ?

C:\Users\user\AppData\Roaming\.homeassistant\deps\Python38\site-packages\zeroconf\__init__.py:1538: FutureWarning: <pyShelly.mdns.MDns object at 0x0408ABF8> has no update_service method. Provide one (it can be empty if you don't care about the updates), it'll become mandatory.

## Environment
arch | x86
dev | false
docker | false
hassio | false
installation_type | Unknown
os_name | Windows
os_version | 10
python_version | 3.8.1
version | 0.111.2
virtualenv | false

## Describe the bug
Just this message, my shelly 2.5 for roller shutter, is operationnel.

**Comment by chemelli74** [comment] 2020-06-16 23:01
What version of the plugin are you using ?
Please next time use our template for opening a issue.

Simone

**Comment by Bestchampy** [comment] 2020-06-17 17:04
Hello,

Excuse me, i forget. I use the last stable version 0.1.8

Thanks, Bestchampy

**Comment by rufik** [comment] 2020-06-18 15:41
Same here with HA 0.111.3 and ShellyForHass v0.1.9.beta.2

**Comment by chemelli74** [comment] 2020-07-08 22:38
Cannot reproduce the issue on HASS **0.111.x** and **0.112.x** using **0.1.9b2** of the plugin.

Please update and report back.

Simone

**Comment by rufik** [comment] 2020-07-13 12:33
Same with HA 0.112.4 + ShellyForHass 0.1.9b2:
```
arch | x86_64
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 4.15.0-109-generic
python_version | 3.7.7
timezone | Europe/Warsaw
version | 0.112.4
virtualenv | false
```

HA log:
```
2020-07-13 14:19:27 INFO (MainThread) [homeassistant.setup] Setting up shelly,
2020-07-13 14:19:27 INFO (MainThread) [homeassistant.setup] Setup of domain shelly took 0.1 seconds.,
2020-07-13 14:19:27 INFO (MainThread) [custom_components.shelly] Starting shelly, 0.1.9-b2,
2020-07-13 14:19:27 INFO (MainThread) [custom_components.shelly] pyShelly, 0.1.30,
2020-07-13 14:19:37 INFO (MainThread) [homeassistant.components.light] Setting up light.shelly,
2020-07-13 14:19:40 INFO (MainThread) [homeassistant.components.cover] Setting up cover.shelly,
2020-07-13 14:19:47 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.shelly,
2020-07-13 14:20:26 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.shelly,
/usr/local/lib/python3.7/site-packages/zeroconf/__init__.py:1541: FutureWarning: <pyShelly.mdns.MDns object at 0x7fc7f074f1d0> has no update_service method. Provide one (it can be empty if you don't care about the updates), it'll become mandatory.
```

**Comment by hakana** [comment] 2020-07-13 13:20
This is fixed in 0.1.9-b3

**Comment by chemelli74** [comment] 2020-07-19 20:39
0.1.9b3 released.

Please test and confirm is fully working.

Simone

**Comment by rufik** [comment] 2020-07-23 13:42
0.1.9 here - no more warning. Nice, thank you :)

**Closed** 2020-07-23 14:15 UTC
Labels: bug, fixed, waiting for feedback
