### ISSUE TITLE
Consumption value after turn off

### ISSUE THREAD

**Issue by GoNzCiD** [StyraHem/ShellyForHASS#79] opened 2019-09-30 13:09 UTC
I have test with a shelly 2.5 than when you turn on the switch, the consumption is updated from 0 to a value in the same second. But when you turn off the switch it takes 10 seconds or more to be set to 0 again.

I can see than inmediatelly after switch it off it is updated the consumption value, but it isn't 0.

Is it possible to update consumption time in a shorter interval or maybe to delay the value reading after turn off?

thanks!

**Comment by Misak** [comment] 2019-12-29 20:09
I have also problem with updating consumption values in hass. In roller shutter mode, it is sometimes showing power consumption as 0 and sometimes it is correct, but delayed. I am not sure what the pattern is (if it is while moving up or down), but definitely acting strangely :)

**Comment by GoNzCiD** [comment] 2020-01-03 07:48
Comsumption values are too delayed for me using this, so I finally used a rest call every 5 seconds to read it.

**Comment by Misak** [comment] 2020-01-03 08:14
@GoNzCiD Could you please share the procedure? :)

**Comment by hakana** [comment] 2020-01-03 10:49
I will check this soon

**Comment by chemelli74** [comment] 2020-01-21 10:43
, can you please retest with 0.1.6b6 ? Please update firmware to latest v1.5.7 as well.
Please share also a screenshot of the device details in lovelace.

Thank you,

Simone

**Comment by GoNzCiD** [comment] 2020-01-24 13:18
Hi @chemelli74, I have tested with 0.1.6b6 and latest 0.1.6b8. With firmware 1.5.7 and latest 1.5.8. With same results. 
I've tested a 2.5 and a 1pm devices as lights. Both has the same long delay but one on turn on and other on turn off.
I can share a [video](https://www.youtube.com/watch?v=A4iVKuBAnEo). first sensor is a rest sensor updated each 5s. Second is the sensor of ShellyForHASS.

And here is a pic for the detail of shelly 1PM
![imagen](https://user-images.githubusercontent.com/12912439/73071848-1ecce000-3eb4-11ea-9412-ee3f4735bb01.png)


Thanks

**Comment by hakana** [comment] 2020-01-24 15:25
Sounds like CoAP discovery working but you not get the status by CoAP. You can try to add the igmp_fix flag and see if that will help. It will resend the ADD_MEMBER to the router every minute, some routers need this to work.

You can also specify the scan_interval to 5 and it will poll the REST API every 5 sec, 60 sec is default.

I have also done some changes around consumption for next release (Beta 9), maybe it will help you.

**Comment by GoNzCiD** [comment] 2020-01-24 17:08
I have igmp_fix to true and I have tested with or without scan_interval to 5. But if I rememeber power consumption is not refreshed by scan_interval, it's right?
It takes about 10-15 secs to update when it isn't updated on on/off inmediatly.
I have enabled IGMP & IGMP proxy on asus router with merlin firm.

How I can check if I'm getting the status by CoAP. If you check the video, when switch is turned off at 0:10, consumption is updated at the moment from 22.06W to 21.93W, but not to 0W till next refesh (maybe the value is updated too early?)

I have this configuration and then I declare each device explicity by id.
![imagen](https://user-images.githubusercontent.com/12912439/73087768-5008d880-3ed3-11ea-866e-5c0145d801ce.png)

**Comment by hakana** [comment] 2020-01-24 22:01
You can use this python script to see the CoAP messages, see attribute 111 and 121 for consumption values. Some devices do not report 0 in consumption direct when turning off.

**Comment by chemelli74** [comment] 2020-02-10 14:35
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-02-14 09:56
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-02-14 09:56 UTC
Labels: question
