### ISSUE TITLE
UI Settings not loading and integration hanging

### ISSUE THREAD

**Issue by craigrallen** [StyraHem/ShellyForHASS#233] opened 2020-03-26 11:30 UTC
Following the previous bug for upgrade, the integration kept showing errors in the log and not loading. I downgraded to 0.1.6 and tried to upgrade back to the beta. The beta kept showing red in HACS and the integration did not show shelly, just :configuration.yaml and error Shelly integration not found.

log details, with the integration actually installed, but the name of the integration was missing before the :configuration.yaml

Logger: homeassistant.setup
Source: setup.py:103
First occurred: 12:12:48 PM (1 occurrences)
Last logged: 12:12:48 PM

Setup failed for shelly: Integration not found.

I removed the integration completely, rebooted HACS, but the devices were left in the integration tab as :configuration.yaml. Then re-installed the integration from HACS. The logs still said integration not found. I deleted the integration in HA and this finally removed the devices showing under :configuration.yaml.

Then I added the integration back as an empty / new integration, that installed cleanly, but when I went to the integration and clicked on the cog icon I get the circle for loading constantly and nothing loading.

![image](https://user-images.githubusercontent.com/56693437/77641809-f1a4b880-6f5c-11ea-8959-fb16ac40010e.png)

When you try to cancel the config settings load and click back it stays loading over the top of the page.

![image](https://user-images.githubusercontent.com/56693437/77641987-3a5c7180-6f5d-11ea-80cc-957a8fcae903.png)

Currently, in 0.1.7beta5 it doesn't seem possible to configure the integration. I saw the issue when I had the voluptuous error in the previous bug, but thought it was just related to that error.

config_flow is causing the hang with the following log errors
`
Logger: aiohttp.server
Source: custom_components/shelly/config_flow.py:79
First occurred: 12:19:54 PM (2 occurrences)
Last logged: 12:29:55 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 204, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 62, in post
    handler, context={"source": config_entries.SOURCE_USER}
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 109, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/shelly/config_flow.py", line 75, in async_step_init
    return await self.async_step_user(user_input)
  File "/config/custom_components/shelly/config_flow.py", line 79, in async_step_user
    self.instance = self.hass.data[DOMAIN][self.config_entry.entry_id]
KeyError: 'shelly'

`

**Comment by craigrallen** [comment] 2020-03-26 11:47
On further investigation, if the configuration.yaml has anything other than shelly: in the settings, then it causes the settings to hang. I tested by adding and removing the following to configuration.yaml under the shelly domain and it broke the integration in the UI.

```
  discovery: true  #add all devices (default)
  sensors: #sensors to show, can be override on each device
    - all
```

Is there a way to capture this in the migration? Maybe an error check to tell the user there is a configuration mismatch? I suspect when people upgrade from 0.1.6 to the 0.1.7 they will still have legacy configuration in the yaml file and there is no warning during the change to 0.1.7

**Comment by craigrallen** [comment] 2020-03-26 12:10
The following happens, after installing it (following deleting the old integration). It recreates some devices in the old integration (that was deleted) and creates some in the new integration.

![image](https://user-images.githubusercontent.com/56693437/77645480-0edc8580-6f63-11ea-8588-38aab71ad0a5.png)

**Comment by hakana** [comment] 2020-03-26 13:05
Look like you have added an integration manually and also have it in config.yaml.

Try to delete both integrations and restart HA, do not create the integration manually.

**Comment by chemelli74** [comment] 2020-03-30 14:32
@craigrallen, did you solve your issue ?

Simone

**Comment by chemelli74** [comment] 2020-04-03 12:02
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-04-16 14:46
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-04-16 14:46 UTC
Labels: support, waiting for feedback
