### ISSUE TITLE
event shelly_switch_click stops working

### ISSUE THREAD

**Issue by Stephan296** [StyraHem/ShellyForHASS#255] opened 2020-04-08 13:24 UTC
When i use shelly_switch_click a couple of times, it's stops working.
My automations don't work anymore. After a restart of hass will fix the problem, after a couple of times switching it's the same problem again

**Comment by chemelli74** [comment] 2020-04-09 15:39
Are you on latest firmware from shelly and on 0.1.7 of this plugin ?

Simone

**Comment by Stephan296** [comment] 2020-04-11 17:26
Yes, i am on the latest version of this plugin

**Comment by chemelli74** [comment] 2020-04-11 17:43
I hink it's a HA issue more than a plugin issue. Did you try check with HA community ?

Simone

**Comment by Stephan296** [comment] 2020-04-11 17:59
Why should it be a HA issue, other events are still working. Only the shelly event dont work anymore.

**Comment by hakana** [comment] 2020-04-13 14:14
Can you see any error in your log file?

**Comment by hugodejong** [comment] 2020-04-15 14:31
Would just like to chime in with a 'me too' here!

This is the last part of the log with ShellyForHASS debug info:

https://gist.github.com/hugodejong/3761ac2b1346b04630d1ecb9f4454c04

I use 1 Shelly dimmer and 2 Shelly 1's. The devices all seem to go Unavailable a lot:

![image](https://user-images.githubusercontent.com/53058265/79349472-897f3c00-7f36-11ea-8fd8-d593caa24479.png)

**Comment by hakana** [comment] 2020-04-15 14:44
> Would just like to chime in with a 'me too' here! The events work for around 5 minutes and then suddenly don't work anymore until the next HA restart.
> 
> This is the last part of the log with ShellyForHASS debug info (around the time the events stop working):
> 
> https://gist.github.com/hugodejong/3761ac2b1346b04630d1ecb9f4454c04
> 
> I use 1 Shelly dimmer and 2 Shelly 1's. The devices all seem to go Unavailable a lot:
> 
> ![image](https://user-images.githubusercontent.com/53058265/79349472-897f3c00-7f36-11ea-8fd8-d593caa24479.png)

Have you tried the IGMP fix flag?

**Comment by hugodejong** [comment] 2020-04-15 20:19
> > Would just like to chime in with a 'me too' here! The events work for around 5 minutes and then suddenly don't work anymore until the next HA restart.
> > This is the last part of the log with ShellyForHASS debug info (around the time the events stop working):
> > https://gist.github.com/hugodejong/3761ac2b1346b04630d1ecb9f4454c04
> > I use 1 Shelly dimmer and 2 Shelly 1's. The devices all seem to go Unavailable a lot:
> > ![image](https://user-images.githubusercontent.com/53058265/79349472-897f3c00-7f36-11ea-8fd8-d593caa24479.png)
> 
> Have you tried the IGMP fix flag?

That seems to have fixed it for me, thank you!

**Comment by chemelli74** [comment] 2020-04-17 15:08
@Stephan296, is the IGMP fix working for you as well ?

Simone

**Comment by DrBlokmeister** [comment] 2020-04-18 13:37
Yeah same issue here. The IGMP fix worked yesterday. But today it doesn't work anymore.

**Comment by chemelli74** [comment] 2020-04-22 09:13
@DrBlokmeister and @Stephan296 , how is the situation ?

Simone

**Comment by Stephan296** [comment] 2020-04-29 07:09
@chemelli74 it still working at the moment, but i have made a couple of restarts the last days. I will give you an update within a couple of days. I have another error in your component:

2020-04-29 08:57:41 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 08:57:41 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 08:58:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 08:58:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 08:59:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 08:59:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 09:00:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 09:00:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 09:01:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 09:01:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 09:02:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 09:02:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 09:03:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 09:03:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 09:04:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 09:04:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 09:05:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 09:05:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 09:06:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily
2020-04-29 09:06:42 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily

**Comment by chemelli74** [comment] 2020-04-29 07:39
>I have another error in your component:

In general, new error => new github issue ;-)
 
> 2020-04-29 08:57:41 WARNING (Poll) [pyShelly] Error, 302 Moved Temporarily

Enable debug log (see wiki).
Seems your router redirect a URL to something else.

Simone

**Comment by chemelli74** [comment] 2020-05-04 22:00
Hi all, just to inform that after 3 weeks of inactivities on thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-05-19 22:47
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-05-19 22:47 UTC
Labels: support, waiting for feedback

**Comment by Stephan296** [comment] 2020-05-29 12:23
it don't work anymore with 0.18 and also 0.19 beta
