### ISSUE TITLE
cache load function for battery operated devices

### ISSUE THREAD

**Issue by fverschure** [StyraHem/ShellyForHASS#150] opened 2020-01-15 21:21 UTC
After a reboot entities for battery operated devices show up as unavailable until they have woke up once. As this may take several hours is there a way to implement a cacheload function to show old values until the device is woken up. This is also the case for zwave devices when they are not available.

**Comment by astrandb** [comment] 2020-01-15 21:36
The behaviour is changed in Homeassistant 0.104 that was released a few minutes ago. The devices are still marked as unavailable until wakeup but the UI is not red or yellow any more. It might be wise to wait to refine the restoration of cached values in this component until the global restore function is mature and stable.

**Comment by vistalba** [comment] 2020-01-16 08:16
I will just try out the new 0.104 release now.
I think this is something similar to this https://github.com/StyraHem/ShellyForHASS/issues/128

My Shelly H&T (battery device) sometimes only wake up every 12h. (if there is no bigger change in temp/humidity). 

Everytime I restart HA (because of a config change) all values are lost until the devices report a new value. The whole entity is "unavaiable". In history card I can see the older values. It would be the best to keep the entities of this devices (may be for a grace period of time) and restore entity, last value & timestamp of value.

**Comment by hakana** [comment] 2020-01-16 09:49
Yes, I will try to find a solution to this. If anyone knows how to do this in the latest version please let me know.

**Comment by vistalba** [comment] 2020-01-16 12:58
That would be awesome :)

I just see that HA now shows that "funny" entity.

So after update, you've to wait until it recognize the entity by ShellyforHass.
If you now restart.. it looks like it keeps the entity. (Screenshot)

![image](https://user-images.githubusercontent.com/12324196/72527025-19deaf80-3868-11ea-8a81-a8add43d3bae.png)

So I think it would be enought to just write back the last values registred before restart.

Let me know if I can test something. I'm not familiar with coding.

**Comment by chemelli74** [comment] 2020-01-21 10:24
> So I think it would be enought to just write back the last values registred before restart.
> Let me know if I can test something. I'm not familiar with coding.

IMHO it's something to do with HA, not with ShellyForHASS.
Infact the plugin doesn't store any value anywhere other than in the DB.
If you click on the entity I'm sure you wil lsee thehistory of the sensor and the temperature values.
But the card in the main display ( the one that you screenshotted) shows current values and nothing else.
So HA is working by design.

Simone

**Comment by vistalba** [comment] 2020-01-21 11:10
@chemelli74 Yes... the entities are cached now (0.140.2) but only in history. After a restart there is just "not available" until the sensor reports a value next time.

**Comment by astrandb** [comment] 2020-01-21 13:24
@hakana I found this after some googling around: [https://aarongodfrey.dev/programming/restoring-an-entity-in-home-assistant/](url)

**Comment by hakana** [comment] 2020-02-15 14:56
Fixed in 0.1.6, please verify and close

**Comment by chemelli74** [comment] 2020-02-19 22:54
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by vistalba** [comment] 2020-02-24 16:43
For me it looks like it works.

**Comment by chemelli74** [comment] 2020-02-24 18:45
Thx for confirming.

Simone

**Closed by chemelli74** 2020-02-24 18:45 UTC
Labels: enhancement, fixed, waiting for feedback
