### ISSUE TITLE
Problems with some Shelly  1 PM detection

### ISSUE THREAD

**Issue by Kedryn** [StyraHem/ShellyForHASS#109] opened 2019-12-02 14:27 UTC
As you can see from the pic, i have two Shelly 1 PM,
one is discovered with all values, the other  not. 
Runnin ShellyForHass 0.1.3

![image](https://user-images.githubusercontent.com/12759632/69967116-11305500-1518-11ea-818b-b56d00243df7.png)

**Comment by wifi75** [comment] 2019-12-03 07:09
I'have some problem, then  the component is very slow

**Comment by chemelli74** [comment] 2020-01-22 07:24
@Kedryn ,@wifi75 can you retest with 0.1.6b7 and update to latest firmware 1.5.8 as well ?

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-01-30 15:07
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-02-12 22:25
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-02-12 22:25 UTC
Labels: question
