### ISSUE TITLE
Home assistant crash on 0.18b1

### ISSUE THREAD

**Issue by skrutt** [StyraHem/ShellyForHASS#277] opened 2020-04-24 17:40 UTC
Hi! 

After updating to the new beta, my home assistant have consistently become unavailable after about 24hrs.
Automations does not activate, website unavailable.

No extra information in the logs after restart, all seems to work normally om startup. 

I would like to give more details but there are not many..

Pi 3b
![Screenshot_20200424-193613](https://user-images.githubusercontent.com/3649368/80241109-538f3580-8663-11ea-869f-99b1f0f116ca.jpg)
![Screenshot_20200424-193903](https://user-images.githubusercontent.com/3649368/80241126-5be77080-8663-11ea-9e67-12644862a07a.jpg)

**Comment by koldogut** [comment] 2020-04-25 12:21
Similar problems here, Home assistant works but all shellies marked as unavailable 

more info:

Home Assistant 0.108.9
HACS: 0.24.2
Shelly for hass: 0.1.8.beta.1

No logs ahead ...

**Comment by chemelli74** [comment] 2020-04-25 13:00
Please enable debug log ( see wiki ) and post relevant part.

Simone

**Comment by chemelli74** [comment] 2020-05-01 14:37
Hi all, just to inform that after 3 weeks of inactivities on thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-05-16 22:32
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-05-16 22:32 UTC
Labels: question, support, waiting for feedback
