### ISSUE TITLE
Shelly H&T - Tempurature Offset ignored

### ISSUE THREAD

**Issue by drash1** [StyraHem/ShellyForHASS#111] opened 2019-12-06 20:46 UTC
Hello,
Thank you for this great Plugin, I love Shelly and HASS, so this is realy an incredible added value for me.

It seems that the temperature offset is ignored when you retrieve the temprature of a H&T sensor.

For example, on Shelly web interface I read 17,6°C, with a Temperature Offset of -3.
In HASS the reported temperature is 20,6°C.

The temperature Offset is well applied in the Shelly Wbe interface, but it's ignored when parsed to HASS.

Some times I can see the right value showing up a fraction of second, very weird ...

(I tried with the last beta release 0.1.3)

**Comment by hakana** [comment] 2019-12-06 21:16
Maybe Shelly report different in REST and CoAP. I saw something about that in an internal group. I will check that but I think it should be fixed in firmware not the plugin.

**Comment by drash1** [comment] 2019-12-06 22:50
> Maybe Shelly report different in REST and CoAP. I saw something about that in an internal group. I will check that but I think it should be fixed in firmware not the plugin.

I think you are right, I tested a REST call and the temperature value was right.

Any way to disable the CoAP calls until Shelly get it fixed?

**Comment by hakana** [comment] 2019-12-07 00:04
Yes but then you will get slow response instead...

**Comment by Baumtreter** [comment] 2020-01-13 22:01
The question is if this will be adjusted ever in the FW as it's shown correctly in the app. I have the same issue with the humidity. 
What do you mean with slow response?

**Comment by chemelli74** [comment] 2020-01-22 07:26
@drash1, @Baumtreter can you retest with 0.1.6b7 and update to latest firmware 1.5.8 as well ?

Thank you,

Simone

**Comment by Baumtreter** [comment] 2020-01-22 07:47
Hi Simone! Thanks for your support. I would try it but it seems that the new firmware isn't rolled out yet here in Germany 🤔

**Comment by chemelli74** [comment] 2020-01-30 15:08
> Hi Simone! Thanks for your support. I would try it but it seems that the new firmware isn't rolled out yet here in Germany 🤔

Are you on current latest and still facing the issue ?

Simone

**Comment by Baumtreter** [comment] 2020-01-30 15:44
Yes. 1.5.7 is the latest available Update for the Shelly HT. The issue is from day one.

**Comment by drash1** [comment] 2020-01-30 15:48
> > Hi Simone! Thanks for your support. I would try it but it seems that the new firmware isn't rolled out yet here in Germany 🤔
> 
> Are you on current latest and still facing the issue ?
> 
> Simone

Hello Simone, the last available FW for H&T is 1.5.7. I tried with 0.1.6b9, but the problem still persist.

It should be 20,8°C
![image](https://user-images.githubusercontent.com/9327424/73464787-bbddbc00-437f-11ea-84bf-a4044a853cfd.png)

Also I'm not sure what the Device temperature is? I'm not sure it was there before.

**Comment by chemelli74** [comment] 2020-01-30 15:49
> It seems that the temperature offset is ignored when you retrieve the temprature of a H&T sensor.
> For example, on Shelly web interface I read 17,6°C, with a Temperature Offset of -3.
> In HASS the reported temperature is 20,6°C.

If avaiable, what says http://x.x.x.x/status ?

Simone

**Comment by Baumtreter** [comment] 2020-01-30 15:57
Also here: Thabks for your support. 

It says:

`{"wifi_sta":{"connected":true,"ssid":"MQTT","ip":"xxxxxxxx","rssi":-53},"cloud":{"enabled":true,"connected":false},"mqtt":{"connected":false},"time":"","serial":1,"has_update":false,"mac":"xxxxxxxxxxx","is_valid":true,"tmp":{"value":21.75,"units":"C","tC":21.75,"tF":71.15, "is_valid":true},"hum":{"value":53.5, "is_valid":true},"bat":{"value":80,"voltage":2.81},"act_reasons":["button"],"connect_retries":0,"update":{"status":"unknown","has_update":false,"new_version":"","old_version":"20191216-090428/v1.5.7@c30657ba"},"ram_total":50600,"ram_free":41212,"fs_size":233681,"fs_free":160640,"uptime":19} `

As you can see Humidity is correct at 53.5% 

Here is a screenshot from HA which shows that the offset is not transmitted. 

![6DFF7949-8F12-40F6-B6FA-44E7074E776B](https://user-images.githubusercontent.com/58390861/73465990-81751e80-4381-11ea-9f85-acc936876144.jpeg)

**Comment by chemelli74** [comment] 2020-01-30 16:02
@Baumtreter , please post details on Facebook English Group and tag "Dimitar Dimitrov"; this is the only way to get a fix in the firmware.

Thank you,

Simone

**Comment by Baumtreter** [comment] 2020-01-30 16:23
Would be appreciate if anyone with the same Issue AND a Facebook Account could do that as I don't have one :)

**Comment by chemelli74** [comment] 2020-01-30 17:47
> Would be appreciate if anyone with the same Issue AND a Facebook Account could do that as I don't have one :)

Posted on your behalf.

Simone

**Comment by Baumtreter** [comment] 2020-01-30 18:44
You're the best! Thanks a million!

**Comment by chemelli74** [comment] 2020-01-30 19:46
Shelly recognized the issue and

![image](https://user-images.githubusercontent.com/57354320/73484433-982b6d80-43a1-11ea-9882-a6cdf120a0fb.png)

**Comment by Baumtreter** [comment] 2020-01-30 19:51
Awesome! Thanks a lot Simone! Will keep you posted as soon the update pops up.

**Comment by joelevi** [comment] 2020-02-28 18:38
My Shelly app is set to read H&T temperature values in F, but the HA integration seems to assume it's in C, and does the calculation again.

For example:
 - Sensor 1 is set to F and reports 69.6 degF in the Shelly app
 - Sensor 1 reports 157.23 degF in Home Assistant

**Comment by chemelli74** [comment] 2020-03-09 11:32
Please update to firmware 1.6.0 and recheck,

Simone

**Comment by chemelli74** [comment] 2020-03-18 22:23
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-03-30 06:07
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-03-30 06:07 UTC
Labels: missing in fw, waiting for feedback
