### ISSUE TITLE
Integration with HA (as component)

### ISSUE THREAD

**Issue by rufik** [StyraHem/ShellyForHASS#23] opened 2019-05-29 14:33 UTC
Do you plan to integrate your nice component into HA? It would be nice to see it official :)

**Comment by hakana** [comment] 2019-05-29 14:35
Yes, I only need more time to do that... We have focused to fix the component first, next step is to integrat it with HA. Can you help?

**Comment by rufik** [comment] 2019-05-29 14:49
I'd like to, but free time is missing factor :)
I'm gonna use your component for Shelly 1, 1 PM and 2.5, so I'm kind of tester right now.

**Comment by Danielhiversen** [comment] 2019-06-17 16:37
I can help with an official integration.
The easiest would be if you open a pull request at https://github.com/home-assistant/home-assistant and mark it as a draft.
Then it would be easier to comment and suggest changes.

**Comment by Misiu** [comment] 2019-08-28 14:00
It would be awesome to have an official integration.

- more people could get involved in the development,
- more potential customers for Shelly,
- an even simpler way to install and configure this integration,
- feedback on the code from HA developers

**Comment by hakana** [comment] 2019-08-28 14:10
Yes, I agree. But right now I don't have time to integrate this with HA. If you or some one else can help it will be very good.

**Comment by Misiu** [comment] 2019-09-02 07:48
@Danielhiversen could You help with this?
I'm still very new to Home Assistant and I didn't do any integrations before.
With the initial PR You will get much feedback from HA developers.

**Comment by tofuSCHNITZEL** [comment] 2019-11-22 12:17
@hakana, @Danielhiversen 
 I would like to help with that. 
I think basically it would be enough to just copy everything 
from
<config directory>/custom_components/shelly
to
homeassistant/components/shelly

but I would like to have it integrate to HA like unifi does:
- add it to integrations via gui
- having a list of devices (like unifi has)
- configuring the basic settings via gui (integration menu)

I'm not super familiar with dev for HA but I'm currently reading through the devdocs and probably by looking at how unifi does it should be possible to do it for shelly.

@Danielhiversen would you have time to do it together? I would create a dev branch on my ha fork and copy all the shellyforhass code there. then after inital testing we can create the pullreq against the ha dev branch

**Comment by majuss** [comment] 2019-11-26 11:54
Hi there, I integrated 2 platforms myself into HA und could help you with the development.

**Comment by tofuSCHNITZEL** [comment] 2019-11-26 15:38
@majuss great! How should we go about it?

**Comment by majuss** [comment] 2019-11-26 16:02
I think somebody from us three should create a branch und just start putting all the code into a normal integration. Then I can help with the HA conformity etc.

**Comment by tofuSCHNITZEL** [comment] 2019-11-26 16:05
Alright I will do that.

**Comment by hakana** [comment] 2019-11-26 16:22
I think it better to keep it here until we have a stable version. Move it to HA only complicate development and testing.

**Comment by tofuSCHNITZEL** [comment] 2019-11-26 16:26
sure I understand that... but the project seems pretty stable to me (good job btw ;))
what are the things you think should be taken care of before we think about HA integration?

**Comment by chemelli74** [comment] 2020-01-22 11:32
@rufik, @ tofuSCHNITZEL, can you please recheck with 0.1.6b7 ?

Thank you,

Simone

**Comment by tofuSCHNITZEL** [comment] 2020-01-22 12:37
installed it now. will get back to you.

**Comment by chemelli74** [comment] 2020-01-30 14:56
@tofuSCHNITZEL , any feedback ?

Simone

**Comment by tofuSCHNITZEL** [comment] 2020-01-30 20:24
i've had 0.1.6-beta.8 installed but after a HA restart the battery shelly H&T is displayed as unavailable until a temperature change forces it to wakeup

**Comment by chemelli74** [comment] 2020-01-31 07:43
Hi,

this issue was about integration, and now it's integrated ;-)
Please confirm so we can close.

About the battery, there are other issues (sorry I cannot help as I don't have the device).
Anyway, IMHO, it's working as expected by HA guidelines.

Simone

**Comment by hakana** [comment] 2020-01-31 08:09
@tofuSCHNITZEL Shelly H&T restore work in beta 9

**Comment by colinfrei** [comment] 2020-01-31 08:15
> this issue was about integration, and now it's integrated ;-)
> Please confirm so we can close.

My understanding was that if it's integrated into HA, it'd be visible on this list: https://www.home-assistant.io/integrations/

Is that just a matter of waiting for a release, or am I misunderstanding what you mean by _now it's integrated_?

**Comment by tofuSCHNITZEL** [comment] 2020-01-31 08:26
> this issue was about integration, and now it's integrated ;-)

sorry I mixed up the thread.
yes there is now a "Shelly Smart home" integration. but the weird thing is on the overview of all integrations its shows me 4 symbols (2 for each h&t I have) but if I click on it the table only displays 2 out of 4 entities.

**Comment by tofuSCHNITZEL** [comment] 2020-01-31 08:31
> 
> 
> > this issue was about integration, and now it's integrated ;-)
> > Please confirm so we can close.
> 
> My understanding was that if it's integrated into HA, it'd be visible on this list: https://www.home-assistant.io/integrations/
> 
> Is that just a matter of waiting for a release, or am I misunderstanding what you mean by _now it's integrated_?

no its about having it in the gui under "settings" -> "integrations"

**Comment by tofuSCHNITZEL** [comment] 2020-01-31 08:32
> 
> 
> @tofuSCHNITZEL Shelly H&T restore work in beta 9

confirmed! :)

**Comment by rufik** [comment] 2020-01-31 10:37
Yes, _Shelly smart home_ is visible in Integrations section :)
But if I choose "_Add new integration -> Shelly smart home_" then there is a popup which is empty (no text) and asks me to input something. What is this supposed for?
![image](https://user-images.githubusercontent.com/425558/73532979-162d5a00-441e-11ea-8222-bec3f0575bfc.png)

**Comment by Misiu** [comment] 2020-01-31 10:37
> > this issue was about integration, and now it's integrated ;-)
> > Please confirm so we can close.
> 
> My understanding was that if it's integrated into HA, it'd be visible on this list: https://www.home-assistant.io/integrations/
> 
> Is that just a matter of waiting for a release, or am I misunderstanding what you mean by _now it's integrated_?

@colinfrei at first I thought the same way, but I think it is still too soon to add ShellyForHASS as an official integration (as it is still in beta)
Having the ability to add ShellyForHASS independent is a big plus: you can update to the newest version without the need to wait for a new release of HA. Recently new versions of ShellyForHass were released very often, a lot of things was added, a lot of bugs fixed (thank you @hakana).

All You need to do is use HACS.
Can we add this repo URL into ADD-ON STORE?
![image](https://user-images.githubusercontent.com/1741838/73532964-0d3c8880-441e-11ea-9220-2f4b84c6181e.png)

Will it work?

**Comment by chemelli74** [comment] 2020-01-31 10:44
> But if I choose "Add new integration -> Shelly smart home" then there is a popup which is empty (no text) and asks me to input something. What is this supposed for?

Did you already added "shelly:" to configuration.yaml ?

Simone

**Comment by colinfrei** [comment] 2020-01-31 11:13
I understand the Pro's and Con's. Personally I still prefer it to be a component included in home assistant.

The Add-On Store is primarily for hass.io addons, not home assistant core components, afaik.

**Comment by colinfrei** [comment] 2020-01-31 11:15
I also primarily wanted to make sure we're not mixing things up in this thread. My read of what @rufik asked for was integrating the code into home assistant core. If that's not something you plan to do, it might make sense to close the issue, and open separate issues for other things that came up here :)

**Comment by rufik** [comment] 2020-01-31 12:33
> > But if I choose "Add new integration -> Shelly smart home" then there is a popup which is empty (no text) and asks me to input something. What is this supposed for?
> 
> Did you already added "shelly:" to configuration.yaml ?
> 

Yes.

**Comment by rufik** [comment] 2020-01-31 12:41
> I also primarily wanted to make sure we're not mixing things up in this thread. My read of what @rufik asked for was integrating the code into home assistant core. If that's not something you plan to do, it might make sense to close the issue, and open separate issues for other things that came up here :)

Initially I was thinking about **putting** this integration into HA's core code.
It evolved to development of GUI Integration Configuration as far as I can see.
Two different things. Let's keep this one as first case and open new issue for second case.

**Comment by chemelli74** [comment] 2020-02-02 22:26
Currently author doesn't plan to have ShellyForHASS as an official component. Basically because developping is a lot faster leaving things as they are.
Once the plugin is feature complete and stable I'm sure he will consider.

To summarize current situation:

- adding Shelly to GUI Integration: **done**
- adding Shelly as official component: **won't fix (for now)**

Simone

**Comment by majuss** [comment] 2020-02-03 07:48
@chemelli74 Hass itself is not out of beta, so why should the components be? And "feature complete" can't be archieved since Shelly is launching new products every now and then...

**Comment by Misiu** [comment] 2020-02-03 08:46
@majuss I think @chemelli74 has a good point.
Right now ShellyForHass can have a new version multiple times a day.
If it would be part of Home Assistant you would have to wait week or two for a new feature or a bug fix.
I also would like to see ShellyForHass as an official integration, but I think that still, it is too early for that.

**Comment by rufik** [comment] 2020-02-03 08:52
> Currently author doesn't plan to have ShellyForHASS as an official component. Basically because developping is a lot faster leaving things as they are.

Probably you're all right, we need fast fixes of issues more than official component.


> * adding Shelly to GUI Integration: **done**

And it's very important for now I think to follow HA's development standards. Thanks a lot for this!

**Comment by chemelli74** [comment] 2020-02-05 07:34
Will reconsider integration in future.
Closing for now.

**Closed by chemelli74** 2020-02-05 07:34 UTC
Labels: enhancement, help wanted
