### ISSUE TITLE
[BUG] Shelly H&T integration not showing decimal number

### ISSUE THREAD

**Issue by slamkalukas** [StyraHem/ShellyForHASS#511] opened 2021-01-03 18:49 UTC
## Environment

- ShellyForHASS release with the issue: 
- Last working ShellyForHASS release (if known): n/a
- Home Assistant Core release with the issue:  Home Assistant 2020.12.1
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant OS running in VM

## Describe the bug

The temperature for Shelly H&T is rounded to whole numbers. I would like to see 21.XX part of number as well.

## Steps to Reproduce

N/A

## Expected behavior

I would like to see also decimal number of temperature (and humidity as well)

## Screenshots

![image](https://user-images.githubusercontent.com/26181848/103486211-72ea7f00-4dfc-11eb-8955-1680d99ac1ac.png)

## Traceback/Error logs

```txt

```

**Comment by david-kalbermatten** [comment] 2021-01-05 10:30
Duplicate of #388

**Closed** 2021-01-05 12:48 UTC
