### ISSUE TITLE
Shelly 2.5 sensors don't have upgrade switch

### ISSUE THREAD

**Issue by trezor12** [StyraHem/ShellyForHASS#162] opened 2020-01-23 14:33 UTC
Hello

Shelly 2.5 sensors don't have upgrade switch. The other shellys have it.

**Comment by chemelli74** [comment] 2020-01-23 14:54
@trezor12 , 

I bet you didn't yet receive the new firmawre notification for those. 
Can you check on the app or at  [http://my.shelly.cloud](url) ?

Thank you,

Simone

**Comment by trezor12** [comment] 2020-01-28 07:42
@chemelli74

I meant, that there is existing new firmware, and possible to update shellys manually, but the HA shelly addon did not generate "upgrade switch" for 2.5 shellys. There are "upgrade switches" for my other shelly devices (1, 1PM, dimmer). The 2.5 devices are configured (maybe that is the issue) this way:

shelly:
  discovery: false  
  id_prefix: ""
  show_id_in_name: false
  upgrade_switch: true
  sensors:
    - switch
    - device_temp
    - power
    - rssi
  devices:
    - id: "76G2E8-1"
      entity_id: shelly25-1
      light_switch: true
    - id: "76G2E8-2"
      entity_id: shelly25-2
      light_switch: true
...

**Comment by chemelli74** [comment] 2020-01-29 06:55
Hi @trezor12, upgrade switch will be created for id "76G2E8" and not for each channel.
Try changing your config to:

```
- id: "76G2E8"
entity_id: shelly25-test
light_switch: true
```
and report back.
Thank you,

Simone

**Comment by astrandb** [comment] 2020-01-29 09:52
@trezor12: Are you sure that the id of the device is "76G2E8"? "G" is probably wrong. Characters in id are normally hexadecimals 0-9, A-F

**Comment by chemelli74** [comment] 2020-02-12 22:30
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-02-19 22:46
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-02-19 22:46 UTC
Labels: question
