### ISSUE TITLE
[FR] add a way to tell if a Shelly Door/Window is a door or a window

### ISSUE THREAD

**Issue by tcarlsen** [StyraHem/ShellyForHASS#302] opened 2020-05-14 07:54 UTC
As default all my Shelly Door/Window sensors comes in as door sensors (with door icon (open closed). It would be nice to be able to tell ShelleForHASS that thius is a window sensor and then use the window icons (open and closed)

**Comment by chemelli74** [comment] 2020-05-15 16:27
Is this setting there in Shelly's app ?

Simone

**Comment by tcarlsen** [comment] 2020-05-15 18:43
dont thing so. so i was think of something like 

```yaml
shelly:
  discovery: true
  devices:
    - id: '5s67as7'
    type: window
```

**Comment by GoSpursGoNL** [comment] 2020-05-23 07:19
In HA you can configure/override the icon for entities, wouldn't that be sufficient?

**Comment by tcarlsen** [comment] 2020-05-23 08:58
Not really. Because then you inly have one icon. Not an open and a closed one

**Comment by chemelli74** [comment] 2020-05-23 09:04
> Not really. Because then you only have one icon. Not an open and a closed one

Why not ? You can do a sensor template with two custom icons based on your preferences.

Simone

**Comment by chemelli74** [comment] 2020-06-04 21:42
Hi all, just to inform that after 3 weeks of inactivity on thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-06-14 12:38
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-06-14 12:38 UTC
Labels: enhancement, waiting for feedback
