### ISSUE TITLE
ip config problem

### ISSUE THREAD

**Issue by madmicio** [StyraHem/ShellyForHASS#223] opened 2020-03-18 18:36 UTC
last beta.
add thids config to lovelace:
`
shelly:
  discover_by_ip:
    - '192.168.1.75'
`

my idea was to integrate only my shelly em, but with this config I find all my shelly in home assistatnt integration.
another problem missing volt data!

**Comment by chemelli74** [comment] 2020-03-18 22:20
For the first problem, as per read.me, add 

`discovery: false`

For the second one, add 

```
sensors:
     -all
```

Recheck and report back,

Simone

**Comment by madmicio** [comment] 2020-03-19 10:46
with:
`discovery: false
`
no device found

**Comment by catalinbordan** [comment] 2020-03-24 19:11
with discovery false you have to specify witch ip should add
like this:
shelly:
  discovery: false
  discover_by_ip:
    - '192.168.5.44'
    - '192.168.32.11'

**Comment by chemelli74** [comment] 2020-03-27 14:58
@madmicio, do you need anything more or we can close this issue ?

Simone

**Comment by madmicio** [comment] 2020-03-27 17:53
in the end I used the integration by decive id, but I still can't get the  voltage data.

**Comment by catalinbordan** [comment] 2020-03-27 18:02
I have it in atributes from shelly 2.5 and EM

**Comment by chemelli74** [comment] 2020-03-27 20:19
> in the end I used the integration by decive id, but I still can't get the voltage data.

Please repost your current config and confirm you are using the latest firmware from Shelly and latest beta from this plugin.

Simone

**Comment by madmicio** [comment] 2020-03-28 12:01
![consumo-conteggio](https://user-images.githubusercontent.com/42836292/77822550-28f99d80-70f4-11ea-8940-3aacf06fc49b.JPG)
![integrazioni](https://user-images.githubusercontent.com/42836292/77822554-2c8d2480-70f4-11ea-98e6-2d587a7a5521.JPG)

**Comment by madmicio** [comment] 2020-03-28 12:01
![shelly conf](https://user-images.githubusercontent.com/42836292/77822571-475f9900-70f4-11ea-8bc6-b71095c93247.JPG)
![integrazioni](https://user-images.githubusercontent.com/42836292/77822572-49295c80-70f4-11ea-81c6-a5bf9c6177a1.JPG)

**Comment by chemelli74** [comment] 2020-03-30 06:08
@madmicio , screenshot shows entities; but voltage is an attribute. Double click on a entities to show it.

Simone

**Comment by madmicio** [comment] 2020-03-30 09:21
scusa Simone, 
ma se faccio doppio click sull'immagine mi appare il secondo screenshot
on duoble click I see the second screenshot

**Comment by chemelli74** [comment] 2020-03-31 07:21
@madmicio, your screenshot is not showing entities attributes. You are looking at entities from configuration.

Instead go in home, select an entity and double click it.
You should see something like this:

![image](https://user-images.githubusercontent.com/57354320/77998043-bfb29e00-7330-11ea-9f4a-8417bc99de49.png)

Attrbitues are highlighted by the yellow box.

Simone

**Comment by madmicio** [comment] 2020-03-31 17:10
![em](https://user-images.githubusercontent.com/42836292/78054974-2660a780-7383-11ea-9dba-eeb4b4ded240.JPG)
I tried to click on all the entities related to shelly em. but I only got these results

**Comment by chemelli74** [comment] 2020-04-01 09:37
> I tried to click on all the entities related to shelly em. but I only got these results

Seems you are using default attributes. Did you check [read.me](https://github.com/StyraHem/ShellyForHASS/blob/master/README.md) carefully ?

Please try adding:

```
attributes:
  -all
```

to your config.
unfortunately I don't have a EM installed, waiting for mine to be delivered.

Simone

**Comment by chemelli74** [comment] 2020-04-01 11:47
> ![error](https://user-images.githubusercontent.com/42836292/78124818-83ef0580-7410-11ea-8341-675770f62645.JPG)
> in this way it gives me configuration error

Attributes is badly indented. Should be at "devices" level not at "id" level.

Simone

**Comment by chemelli74** [comment] 2020-04-03 12:01
@madmicio, did you solve your issue ?

Simone

**Comment by madmicio** [comment] 2020-04-06 09:38
No :-(

**Comment by chemelli74** [comment] 2020-04-06 09:50
> No :-(

Did you fix the config file as suggested ?
Can you repost current shelly config ?

Simone

**Comment by madmicio** [comment] 2020-04-06 13:49
![attuale](https://user-images.githubusercontent.com/42836292/78565191-d4ee6780-781d-11ea-89ed-43c554d17cb7.JPG)

if you are referring to the shelly_for_hass configuration, it is this!
otherwise in the shelly configuration I have no parameters to mark. cloud enabled and nothing else

**Comment by chemelli74** [comment] 2020-04-10 09:24
@madmicio any news ?

Simone

**Comment by chemelli74** [comment] 2020-04-16 14:49
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by madmicio** [comment] 2020-04-16 15:17
No news. Update but no voltage

**Comment by hakana** [comment] 2020-04-16 15:38
Should work in latest release, please test.

**Comment by chemelli74** [comment] 2020-04-17 12:35
@madmicio, just to clarify: latest is 0.1.8b1.

Simone

**Comment by madmicio** [comment] 2020-04-17 16:14
I have updated shelly_for_ass
I canceled the old integration,
I cleared the configuration in configuration.yaml
restarted
rewritten the configuration in consiguration.uaml
restarted
result as in the photo.
no voltage
![energy](https://user-images.githubusercontent.com/42836292/79590428-4d371180-80d7-11ea-8022-cec3af6adfc9.jpg)

**Comment by chemelli74** [comment] 2020-04-18 08:34
Can you please add the device without the channel ( "-1" / "-2" ) ?

Simone

**Comment by madmicio** [comment] 2020-04-18 10:11
![Schermata 2020-04-18 alle 12 11 10](https://user-images.githubusercontent.com/42836292/79634912-c1bc8f80-816d-11ea-88a9-294115be044c.png)

perfect!

**Comment by chemelli74** [comment] 2020-04-18 13:02
Issue solved, closing.

Simone

**Closed by chemelli74** 2020-04-18 13:02 UTC
Labels: support, waiting for feedback
