### ISSUE TITLE
When a Shelly entity is disabled, an error is shown in the HA log.

### ISSUE THREAD

**Issue by jeroenvdwaal** [StyraHem/ShellyForHASS#75] opened 2019-09-22 08:49 UTC
First of all, thanks for making this great extension to HA.

I hope to help you out with the following message in the log. In the recent Home Assistant version 98.0, a new feature became available to suppress/disable a device from appearing in Home Assistant. The HA page is called entity-register, accessible via settings. When clicked on an item, a switch is now visible to disable the entity.

I think that the suppression is up to the component to implement. HA is only doing the administrative task. 

The Shelly in the error message below is removed from the interface because it should never be switched off. It is used for power measurement only. So the switch entity of the Shelly is the one that is disabled.

2019-09-22 10:27:10 WARNING (MainThread) [homeassistant.helpers.entity] Entity switch.shelly_shplg_s_79ca2c is incorrectly being triggered for updates while it is disabled. This is a bug in the shelly integration.

Keep up the good work!

**Comment by chemelli74** [comment] 2020-01-21 10:40
@jeroenvdwaal, can you please retest with 0.1.6b6 ?

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-01-26 19:21
Duplicate of #96 

Simone

**Closed by chemelli74** 2020-01-26 19:21 UTC
Labels: duplicate
