### ISSUE TITLE
[BUG] | [FR] New CoAP description in FW 1.8

### ISSUE THREAD

**Issue by vistalba** [StyraHem/ShellyForHASS#366] opened 2020-08-05 19:16 UTC
As stated here, there will be a breaking Change with Firmware 1.8.

https://www.facebook.com/groups/ShellyIoTCommunitySupport/permalink/3002067616559249/

As ShellyForHass is using CoAP I think a update is needed.

**Comment by chemelli74** [comment] 2020-08-05 20:29
We are already working on making ShellyForHASS compliant to new firmware specs.
Stay tuned.

Simone

**Comment by robinostlund** [comment] 2020-08-12 14:24
Any updates on this one? As they have started to roll out the updates 😊

**Comment by mrulke** [comment] 2020-08-13 00:36
saw the dev release. happy help with testing as i have updated my dimmer 2 to the 1.8 firmware to stop flickering.
do I just copy the dev branch over the top of the current install?

**Comment by Tom7320** [comment] 2020-08-13 08:14
I can confirm that it definitely is a breaking change with 1.8. Unfortunately I updated all my shellys to 1.8 and now I can't control them anymore from HA. Since I have a lot of Shellys I would like to ask if there is another easy way to fix the issue without waiting for the next ShellyForHASS release? I would also suggest to rate this issue as a bug instead of a feature request.

**Comment by vistalba** [comment] 2020-08-13 08:19
@Tom7320 
Just downgrade your all affected shelly‘s?

`http://[IPOFSHELLY]/ota?url=[URLTOOLDERFIRMWARE]`

You just need the older FW files hosted on a Webserver and replace the values above.
Important: use the correct FW file per device. You need to execute it once per device. Battery operated devices need to be waked up before hitting the URL.

**Comment by artkrz** [comment] 2020-08-13 08:21
No offence guys, but CoAP changes were announced in advance and making ShellyForHASS ready for it should be priority. I realise you're probably doing this in your free time and I'm grateful but this should be fixed and fv rollback isn't really an option for all since 1.8 fixed major issues with dimmer overloading and other shelly device restart problems.

**Comment by Tom7320** [comment] 2020-08-13 08:25
Well I agree. I don't want to downgrade. And I certainly can wait a couple of days. It's just that I can not control my shutters anymore, and we have over 35°C today.... 🔥

**Comment by vistalba** [comment] 2020-08-13 08:30
Please be patient.
I‘m waiting too.
8 days ago they announced that change. I‘m sure the developers of ShellyforHASS didn‘t wait for that change and now have to fix a lot of things (in their free time) for every device.
8 days is not a lot of time, so downgrade Shelly FW to < 1.8 if controling in HA is important to you or wait until new Shellyfor HASS version is ready. I know it‘s not nice but it is how it is at the moment.
I‘m sure the devs know about the importance of this issue.

**Comment by vistalba** [comment] 2020-08-13 08:32
> Well I agree. I don't want to downgrade. And I certainly can wait a couple of days. It's just that I can not control my shutters anymore, and we have over 35°C today.... 🔥

Downgrade.... 2.5 in roller shutter really didn‘t have any issues as I‘m using it too. So „i don‘t want to...“ really doesn‘t matter.

**Comment by Tom7320** [comment] 2020-08-13 08:38
![image](https://user-images.githubusercontent.com/19165864/90113031-0c7f9a00-dd51-11ea-9112-aa47f1840854.png)

What's the newest firmware before 1.8.0? 1.6.1? There was no 1.7?

**Comment by Tom7320** [comment] 2020-08-13 08:40
Never mind. Found it. https://www.shelly-support.eu/index.php?shelly-firmware-archive/

**Comment by vistalba** [comment] 2020-08-13 08:44
@Tom7320 depends on device. My 2.5 is on v1.7.4 at the moment which is working fine with HA.

Didn‘t find that Version... but I‘ve found two for you...

`http://1.2.3.4/ota?url=http://archive.shelly-support.eu/v1.7.7/SHSW-25_build.zip`

`http://1.2.3.4/ota?url=http://archive.shelly-support.eu/v1.7.0/SHSW-25_build.zip`

Just replace `1.2.3.4` with the IP of the Shelly 2.5 you want to downgrade.

**Comment by Tom7320** [comment] 2020-08-13 09:08
Downgraded. Works again. Thx a lot!

**Comment by GoNzCiD** [comment] 2020-08-15 20:36
I have updated several devices and I'm having this error too, I'm going to test the dev version as @mrulke said...

**Comment by hakana** [comment] 2020-08-15 21:37
> saw the dev release. happy help with testing as i have updated my dimmer 2 to the 1.8 firmware to stop flickering.
> do I just copy the dev branch over the top of the current install?

dev branch is just for development team to share code, it is very unstable. Please not use!

**Comment by Soylor** [comment] 2020-08-16 21:13
I dis solve it until new shellyforhass is published using Shely DDD and rest API.
Configured as Entities instead of devices but working fine until new version available.

**Comment by IATkachenko** [comment] 2020-08-17 17:53
> We are already working on making ShellyForHASS compliant to new firmware specs.
> Stay tuned.

@chemelli74, @hakana, hello.
Is any public activity available for this? Community may take a part too.

ps. Bumping pyShelly to master@github version is solving my issues.

**Comment by chemelli74** [comment] 2020-08-17 18:49
> > We are already working on making ShellyForHASS compliant to new firmware specs.
> > Stay tuned.
> 
> @chemelli74, @hakana, hello.
> Is any public activity available for this? Community may take a part too.
> 

Working hard on the release, pleas ebe patient a little bit more.

> ps. Bumping pyShelly to master@github version is solving my issues.

We kindly ask not to mix up things testing with master/dev/whatever.
Thx for the cooperation.

Simone

**Comment by artkrz** [comment] 2020-08-23 17:23
No hard feelings guys, I do appreciate your work and was happy with this integration so Thank You. However, I'm done waiting and looks like MQTT is the way forward. To others that don't want to wait any longer, remember, this is free software, you can always go elsewhere. Good luck.

**Comment by mathewmeconry** [comment] 2020-08-24 11:22
Is there a way that I can help you guys to get this update done? Testing, developing or something else?

**Comment by msekoranja** [comment] 2020-08-26 08:26
The biggest pain is not knowing about progress, timeline. A day, a week, a month or never - it's OK (this is a open-source project), it is just good to be informed.

**Comment by kauha** [comment] 2020-08-26 10:28
I'm also stuck on 1.8+ on RGBW2 and for some reason downgrade doesn't work (tried hosting the file on LAN too..) so a timetable would be nice. Also willing to help in progress if possible

**Comment by radubatori** [comment] 2020-08-26 10:48
@kauha Downgrading RGBW2s did not work for me as well, but enabling MQTT and using something like [this](https://github.com/thehookup/Shelly-RGBW2) is a good enough workaround for now. I know it's not ideal and I hope this great library gets updated soon.

**Comment by stevearmitage** [comment] 2020-08-27 00:11
The Facebook party today stats that you can access them beta from here today or HACS tomorrow. I'll download the HACS update tomorrow. Thanks for keeping the plugin updated.

**Comment by NickDePooter** [comment] 2020-08-27 18:21
After installing the Beta version I still keep getting this errors:

2020-08-27 20:13:13 ERROR (Thread-141) [pyShelly] Timeout connecting to http://192.168.0.224/status [192.168.0.224]
2020-08-27 20:13:23 ERROR (Thread-142) [pyShelly] Timeout connecting to http://192.168.0.224/status [192.168.0.224]
2020-08-27 20:13:23 ERROR (Thread-143) [pyShelly] Timeout connecting to http://192.168.0.224/status [192.168.0.224]

Any ideas or people with the same issue?

**Comment by Soylor** [comment] 2020-08-27 19:16
Every thing fine after dowgradimg to 1.7 firmware

**Comment by thecem** [comment] 2020-08-28 07:52
Thanks a lot! EM3 are working!
But shelly 2.5 in shutter mode do not have status, only after boot it is for a few seconds visible (the shutters working in homebridge-shelly an are calibrated).
So if the shutter is closed you have only the possibility to close it, because ha 0.104.4 is assuming all are open...

**Comment by vistalba** [comment] 2020-08-28 09:46
> Thanks a lot! EM3 are working!
> But shelly 2.5 in shutter mode do not have status, only after boot it is for a few seconds visible (the shutters working in homebridge-shelly an are calibrated).
> So if the shutter is closed you have only the possibility to close it, because ha 0.104.4 is assuming all are open...

Is reported here: https://github.com/StyraHem/ShellyForHASS/issues/399

**Comment by chemelli74** [comment] 2020-08-28 21:16
Support for firmware 1.8 added in 0.2.0b1 version.

If you have any further issue, please open a specific and detailed issue.

Simone

**Closed** 2020-08-28 21:16 UTC
Labels: enhancement, investigating
