### ISSUE TITLE
[BUG] Shelly Plug does not show device_temp

### ISSUE THREAD

**Issue by Gawronnek** [StyraHem/ShellyForHASS#340] opened 2020-07-01 15:26 UTC
ShellyForHASS release with the issue: 0.1.8
Last working ShellyForHASS release (if known):
Home Assistant Core release with the issue: 0.111.4
Operating environment HassOS 4.10

![Zrzut ekranu 2020-07-01 17 25 18a](https://user-images.githubusercontent.com/55258190/86262584-5c027000-bbc0-11ea-9aaa-010d6ba6896e.png)

**Comment by chemelli74** [comment] 2020-07-02 12:52
Works fine here with 0.1.9b2.
Please review also your config based on https://github.com/StyraHem/ShellyForHASS/blob/master/README.md

Simone

**Comment by Gawronnek** [comment] 2020-07-02 14:01
my config 
shelly:
  discovery: true
  settings:
    temperature: { decimals: 1 }
    current_consumption: { decimals: 2 }  
  sensors:
    - all

![Zrzut ekranu 2020-07-02 15 59 53](https://user-images.githubusercontent.com/55258190/86368166-2b344080-bc7d-11ea-9ded-e4284971da37.png)

**Comment by chemelli74** [comment] 2020-07-27 07:38
@Gawronnek, do you see the temp value if you check on status page ? Link is http://<shelly-ip>/status

Simone

**Comment by chemelli74** [comment] 2020-08-01 12:42
Hi all, just to inform that after 3 weeks of inactivity on thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-08-28 21:12
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-08-28 21:12 UTC
Labels: support, waiting for feedback
