### ISSUE TITLE
Shelly 2.5 still no current temperature and not update sensor

### ISSUE THREAD

**Issue by max-rh** [StyraHem/ShellyForHASS#184] opened 2020-02-09 07:58 UTC
Hi,
First I would like to thank you for such an amazing integration.

I have been running this integration for a long time and it has been working perfectly, but I don't know at what version the issue appeared, but I have multiple Shelly plugs, 1 and 2.5 all working perfectly; all my 2.5 Shellies are working in Roller mode and working perfectly in the integration and I get all sensors except for one 2.5 shelly that is running in Dual Relay for 2 loads, its working fine with the integration but I am no longer getting 3 sensors for this Shelly : 
 - the current temperature sensor 
 - the over temp sensor
 - the update sensor.

I am running the following latest versions: 
 - HA 0.105.2
 - ShellyForHass: 0.1.6
 - Shelly 2.5 Firmware: 20200206-083126/v1.5.10@e6a4205e

this issue only affects the shelly 2.5 when running in **relay mode**.
I have noticed that there is a similar issue opened regarding this, but the latest ShellyForHass did not fix this and my Shelly global configuration are as follows:

shelly:
  discovery: false
  version: true
  sensors:
    - all

and none of the configuration of my devices overwrite the global config, my devices configurations only include (name and ID).

I appreciate any advice on this.

**Comment by chemelli74** [comment] 2020-02-09 14:10
Can you post a screenshot of HA rappresenting this issue ?
I want to check if I got it right.

Simone

**Comment by chemelli74** [comment] 2020-02-19 23:00
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by niklasfink** [comment] 2020-02-21 20:47
Hi @chemelli74, I'm running default settings with just `shelly:` in my configuration.yaml and I'm missing temperature readings for all Shelly 2.5s:

![image](https://user-images.githubusercontent.com/1809301/75070551-b47b7f80-54f3-11ea-9421-9b82fbc97fe2.png)

**Comment by chemelli74** [comment] 2020-02-21 21:59
You posted a screenshto of a Shelly in roller mode, but issue is about relay mode...

Simone

**Comment by niklasfink** [comment] 2020-02-21 22:06
Hey @chemelli74, it seems like it doesn't matter which mode it is, as temperature information is given independent to the mode (for example via MQTT) and should therefore be available.

It seems that it cannot be narrowed down to Relay Mode, as this problem is also appearing for me with Roller mode. (Except I'm doing something wrong) 
Given the generic naming of this issue, I think this fits in here, but I can of course also create a new issue.

**Comment by chemelli74** [comment] 2020-02-21 23:00
Works fine here:

![image](https://user-images.githubusercontent.com/57354320/75078571-3d031b80-5506-11ea-8135-d1a53481d50d.png)

Simone

**Comment by niklasfink** [comment] 2020-02-22 08:24
Did you manually enable these stats in your configuration.yaml? I understood the readme that all sensors are enabled by default.

**Comment by hakana** [comment] 2020-02-22 08:33
sensors: -all should enable all sensors.  Can you check if you have any errors in log?

**Comment by niklasfink** [comment] 2020-02-22 09:41
Explicitly setting sensors: -all solved it

**Comment by chemelli74** [comment] 2020-02-22 22:39
@max-rh di you manage to fix your problem ? Can we close this issue ?

Simone

**Comment by max-rh** [comment] 2020-02-22 23:10
Hi @chemelli74, so sorry for the late reply.
unfortunately no, the issue is still present... and yes i do have "-all" explicitly defined.

**Comment by chemelli74** [comment] 2020-02-22 23:11
> Hi @chemelli74, so sorry for the late reply.
> unfortunately no, the issue is still present... and yes i do have "-all" explicitly defined.

can you share debug log, configuration.yaml and screenshot ?

Simone

**Comment by max-rh** [comment] 2020-02-22 23:46
@chemelli74 
Here is my configuration.yaml:
![image](https://user-images.githubusercontent.com/25219094/75100946-b6ba0880-55dd-11ea-8582-04964674ad36.png)

and here is that shelly's integration:
![image](https://user-images.githubusercontent.com/25219094/75100964-2cbe6f80-55de-11ea-9faf-beb324a4a8cb.png)


as for the debug; i am not seeing any logs regarding my shellies.

Thanks

**Comment by chemelli74** [comment] 2020-02-23 09:44
> @chemelli74
> Here is my configuration.yaml:

why discovery false ?

Simone

**Comment by max-rh** [comment] 2020-02-23 23:14
Hi @chemelli74 ,

I have alot of shellies and alot more to install and they are located behind multiple VLANs, so turning discovery on makes managing them a nightmare, so i have all my shellies statically assigned via my DHCP server and i add them manually to help manage them.

But turning off discovery never been an issue, this issue only happened few releases ago.

Thanks

**Comment by chemelli74** [comment] 2020-02-24 13:21
Can you enable debug log and share ?

Simone

N.B: Can it be that you disabled some entities in the past ?

**Comment by max-rh** [comment] 2020-02-27 08:10
Hi, @chemelli74 sorry for the delay,
No, I haven't disabled any entities in the past,

could you please explain how to enable the ShellyForHass log and share it?, or do you mean the HA log ?

**Comment by chemelli74** [comment] 2020-02-27 09:47
> could you please explain how to enable the ShellyForHass log and share it?, or do you mean the HA log ?

https://github.com/StyraHem/ShellyForHASS/wiki/FAQ4:-Enable-debug-log

Simone

**Comment by chemelli74** [comment] 2020-03-08 19:33
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-03-18 22:22
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-03-18 22:22 UTC
Labels: waiting for feedback
