### ISSUE TITLE
[FR] Add support for Shelly button1

### ISSUE THREAD

**Issue by ronschaeffer** [StyraHem/ShellyForHASS#344] opened 2020-07-08 13:55 UTC
## Is your feature request related to a problem? Please describe.

No

## Describe the solution you'd like

Add support for the new Shelly button1 WiFi button. Functions would include:

binary_sensor to fire click_type events for  button presses similar to the [Xiaomi Binary Sensor / Button (2nd gen, model b) / sensor_switch.aq3](https://www.home-assistant.io/integrations/binary_sensor.xiaomi_aqara/).

Necessary click_type events are:
single

- `single `(equivalent to "S" in the button1's MQTT payload)
- `double `(equivalent to "SS" in the button1's MQTT payload)
- `triple `(equivalent to "SSS" in the button1's MQTT payload)
- `long_click_release` (equivalent to "L" in the button1's MQTT payload)

Attributes of the binary_sensor would mirror those in the MQTT announce topic. An example:

```
{
"id":"shellybutton1-A4CF12F45174",
"mac":"A4CF12F45174",
"ip":"192.168.86.53",
"new_fw":false,
"fw_ver":"20200625-102446/v1.7.3@2aa0993a"
}
```

Additional sensors for:

- battery
- WiFi RSSI
- online status

MQTT payloads for button press events also include `event_cnt`. Perhaps there is a reason to also support `event_cnt`? As seen in MQTT Explorer:

![image](https://user-images.githubusercontent.com/12379923/86927073-c3717000-c12a-11ea-8908-142cc7cf6471.png)

event_cnt appears to be a simple counter of each sent button press event while the button is connected to the MQTT broker. While on USB power, the count increments with each button event. While on battery power, the count appears not to increment, presumably because the button1 disconnects between events.

## Describe alternatives you've considered

Alternatives are to enable MQTT and set up automations to be triggered by button press payloads or to enter HA webhooks for each of the button press types into the button1 device management UI.

**Comment by robinostlund** [comment] 2020-07-11 14:05
I would also like to use this :)

**Comment by david-kalbermatten** [comment] 2020-07-14 08:54
this seems to be a duplicate of #335 (although, a bit more descriptive than the original one)

**Comment by chemelli74** [comment] 2020-07-17 21:51
> this seems to be a duplicate of #335 (although, a bit more descriptive than the original one)

Thx for pointing out.

Simone

**Closed by chemelli74** 2020-07-17 21:51 UTC
Labels: enhancement
