### ISSUE TITLE
[FR] long press event

### ISSUE THREAD

**Issue by colinfrei** [StyraHem/ShellyForHASS#206] opened 2020-03-01 15:14 UTC
It'd be nice to be able to identify long presses. Afaict shelly itself allows adding events for that, but I don't seem to be able to recognize that a press was a long press on home assistant.
I'm using a shelly 1 and a 2.5

**Comment by colinfrei** [comment] 2020-03-05 14:54
As far as I can tell, the state change doesn't actually wait for the button click, but listens for a state change of the button. Accordingly, it wouldn't be easy to figure out that a long press caused the state change.

An alternative I'm looking into now is using mqtt events. What would be nice was if it were easy to set up HA's mqtt on the shelly devices (as well as change the configuration in general. I'm going to play around with options to do that, and may make a merge request for that when I have something.

**Comment by vistalba** [comment] 2020-03-09 14:50
Using Shelly 1, 1pm, 2.5 and Dimmer and would also like  to use "longpush" events as trigger for some automations.

Example:
If light of Shelly is of and longpush event detected on this "Switch" then switch off (all) other lights.

**Comment by chemelli74** [comment] 2020-05-23 09:11
What about enabling debug log and look if CoAP-msg for long press is received ?

Simone

**Comment by chemelli74** [comment] 2020-06-04 21:40
Hi all, just to inform that after 3 weeks of inactivity on thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-06-14 12:38
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-06-14 12:38 UTC
Labels: enhancement, waiting for feedback
