### ISSUE TITLE
Firmware update call fail

### ISSUE THREAD

**Issue by davanda** [StyraHem/ShellyForHASS#259] opened 2020-04-10 16:57 UTC
detects need for updating and its switch.shelly_shsw_1_xxxxxx_firmware_update appears, 
but the call fails when I activate it.

Can you help?
thk!

**Comment by chemelli74** [comment] 2020-04-10 22:33
> detects need for updating and its switch.shelly_shsw_1_xxxxxx_firmware_update appears, 
> 
> but the call fails when I activate it.
> 
> 
> 
> Can you help?
> 
> thk!

Please check wiki and post debug log.

Simone

**Comment by chemelli74** [comment] 2020-04-16 14:47
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-05-03 10:04
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-05-03 10:04 UTC
Labels: support, waiting for feedback
