### ISSUE TITLE
[BUG] Switch status toggling repeatedly 

### ISSUE THREAD

**Issue by wreality** [StyraHem/ShellyForHASS#290] opened 2020-05-04 01:43 UTC
## Environment

- ShellyForHASS release with the issue: 0.1.8
- Last working ShellyForHASS release (if known): Unknown
- Home Assistant Core release with the issue: 0.109.3
- Operating environment (Home Assistant/Supervised/Docker/venv): Hassio

## Describe the bug

I'm not sure if this is a Shelly problem or a ShellyForHASS problem.  I have a couple of Shellys that will start toggling their switch states in HA.  The output itself doesn't toggle and rebooting via the Shelly web GUI doesn't seem to fix it.  The only thing I can point to fixing it is a hard power off / on of the Shelly, but the problem seems to come back eventually.

## Steps to Reproduce
Not entirely sure what's causing this to start.

## Screenshots

![image](https://user-images.githubusercontent.com/463159/80931277-bb8dfc00-8d86-11ea-9599-74e75c5ed15a.png)

## Traceback/Error logs

```txt

```

**Comment by hakana** [comment] 2020-05-04 08:30
Can you see any errors in HA log?
Are all your devices doing this?
Do you have a switch connected?

**Comment by wreality** [comment] 2020-05-04 22:49
I’ve not been able to find anything in the HA logs.  Only two of my Shelly’s seem to do this. (I also have other Shelly 1 PM’s that don’t have this problem.)

Both have a switch connected. One is in detached mode to trigger an automation (which is disabled now bc of the problem causing the trigger to happen repeatedly). The other is in edge mode. The physical switch does exactly what it’s supposed to as well as remote control from HA. It appears only to be the switch state that HA is seeing. (Which for this Shelly  I’m not actively using)

Any other thoughts as to logs I can enable or access that might help debug the issue?

**Comment by chemelli74** [comment] 2020-05-04 23:35
Which are the protocols in the entity details ?

Simone

**Comment by wreality** [comment] 2020-05-04 23:58
CoAP-discovery, poll, CoAP-msg, mDns

**Comment by hakana** [comment] 2020-05-05 12:05
What is the button type selected in the Shelly app for the device?

You can try to enable debug logs for Shelly:
https://github.com/StyraHem/ShellyForHASS/wiki/FAQ4:-Enable-debug-log

I have tested with a Shelly 1PM here and it working as it should. So I think the problem is more likely the switch or Shelly.

**Comment by chemelli74** [comment] 2020-05-23 09:06
Hi all, just to inform that after 3 weeks of inactivity on thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-05-26 18:39
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-05-26 18:39 UTC
Labels: support, waiting for feedback
