### ISSUE TITLE
Settings panel is too long in 0.1.7 beta 1

### ISSUE THREAD

**Issue by Misiu** [StyraHem/ShellyForHASS#209] opened 2020-03-06 01:02 UTC
The setting window is too long:
![image](https://user-images.githubusercontent.com/1741838/76040035-7ef08080-5f4e-11ea-8fe9-70565536d16f.png)
I had to zoom out to be able to see the `Submit` button

**Comment by chemelli74** [comment] 2020-03-09 22:45
Confirmed.

Simone

**Comment by chemelli74** [comment] 2020-03-14 09:34
Please update to latest beta (0.1.7.b2) and recheck.

Simone

**Comment by Misiu** [comment] 2020-03-14 15:55
@chemelli74 I just updated to 0.1.7.b2 and I have the exact same bug (the panel is still too long).
I have screen resolution 1680x1050.
If I change the zoom to 80% (in Chrome I see the submit button).

**Comment by hakana** [comment] 2020-03-16 18:26
Fixed in 0.1.7.b3

**Comment by Misiu** [comment] 2020-03-18 07:07
Now it looks great!
Thank you.
@chemelli74 you can close this issue now.

**Comment by hakana** [comment] 2020-03-18 10:39
👍

**Comment by Misiu** [comment] 2020-03-18 10:44
@hakana ideally config dialog should allow scrolling if there are large number of options.
There are scrollable containers in Lovelace, I'll create a feature request for adding this to config flow.

**Comment by hakana** [comment] 2020-03-18 10:58
This os controlled by HA so you need to add FR to HA.

**Comment by Misiu** [comment] 2020-03-18 11:22
FR created: https://github.com/home-assistant/frontend/issues/5253

**Comment by bramkragten** [comment] 2020-03-18 12:23
Why not use a multiselect input for this?

**Comment by hakana** [comment] 2020-03-18 13:18
Because HA not supporting that for settings

**Comment by Misiu** [comment] 2020-03-18 15:24
@hakana check for example plex: https://github.com/home-assistant/core/blob/dev/homeassistant/components/plex/config_flow.py#L287 or Unifi https://github.com/home-assistant/core/blob/dev/homeassistant/components/unifi/config_flow.py#L210

**Comment by chemelli74** [comment] 2020-04-09 16:59
With 0.2.0 milestone author will design a completly new GUI for settings so this issue will be superseded.

Closing.

Simone

**Closed by chemelli74** 2020-04-09 16:59 UTC
Labels: bug, fixed
