### ISSUE TITLE
Error when creating version sensor

### ISSUE THREAD

**Issue by uspino2** [StyraHem/ShellyForHASS#83] opened 2019-10-05 04:08 UTC
When `version: true` in config, sensor is not created and I get this error on restart:

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 389, in _async_add_entity
    raise HomeAssistantError(f"Invalid entity id: {entity.entity_id}")
homeassistant.exceptions.HomeAssistantError: Invalid entity id: sensor._version
```

**Comment by chemelli74** [comment] 2020-01-21 10:46
@uspino2 , can you please retest with 0.1.6b6 ? Please update firmware to latest v1.5.7 as well.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-01-30 15:01
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-02-11 15:11
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-02-11 15:11 UTC
Labels: question
