### ISSUE TITLE
HACS Shelly Smart Home

### ISSUE THREAD

**Issue by uaparac** [StyraHem/ShellyForHASS#77] opened 2019-09-28 10:48 UTC
With this latest version 0.1.0 HA does not detect my devices.  No Shelly entities appear.  Anything I'm doing wrong?  I've tried to enter manually or in discovery mode but nothing ...

**Comment by uaparac** [comment] 2019-10-02 08:18
Can you explain this please.
I have 4 Shelly 2.5, 4 shelly 1 and 1 shelly H&T and with this plugin I only get 1 shelly 2.5 on HA.
I am just using this in the yaml file
`shelly:`

I already insert the IDs of the remaining Shellys but HA can not enter their Entities.

**Comment by hakana** [comment] 2019-10-02 11:03
Can you see any errors in the log?

**Comment by uaparac** [comment] 2019-10-02 23:47
I think nothing from Shelly devices

_    _                 _
 | |  | |               (_)
 | |__| | __ _ ___ ___   _  ___
 |  __  |/ _` / __/ __| | |/ _ \
 | |  | | (_| \__ \__ \_| | (_) |
 |_|  |_|\__,_|___/___(_)_|\___/



Our Cli:
$ hassio help

core-ssh:~# hassio ha logs
raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.7/site-packages/jinja2/sandbox.py", line 438, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 805, in strptime
    return datetime.strptime(string, fmt)
TypeError: strptime() argument 1 must be str, not None
2019-10-03 00:42:05 ERROR (MainThread) [homeassistant.components.template.sensor] Could not render template GFT afval: UndefinedError: 'str object' has no attribute 'strftime'
2019-10-03 00:42:05 ERROR (MainThread) [homeassistant.components.template.sensor] Could not render template Plastic: UndefinedError: 'str object' has no attribute 'strftime'
2019-10-03 00:42:05 ERROR (MainThread) [homeassistant.components.template.sensor] Could not render template Restafval: UndefinedError: 'str object' has no attribute 'strftime'
2019-10-03 00:42:05 INFO (MainThread) [homeassistant.components.automation] Initialized trigger Waste collection tomorrow
2019-10-03 00:42:05 INFO (MainThread) [hacs] Loading known repositories
2019-10-03 00:42:05 INFO (MainThread) [homeassistant.core] Timer:starting
2019-10-03 00:42:06 INFO (SyncWorker_13) [root] Sending control command: KEY
2019-10-03 00:42:16 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.waste_tomorrow fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 261, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 441, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/areawaste/sensor.py", line 264, in update
    self._reader.update()
  File "/config/custom_components/areawaste/sensor.py", line 133, in update
    address_id = self._find_unique_address_id()
  File "/config/custom_components/areawaste/sensor.py", line 159, in _find_unique_address_id
    return response['dataList'][0]['UniqueId']
TypeError: 'NoneType' object is not subscriptable
2019-10-03 00:42:17 INFO (SyncWorker_1) [root] Sending control command: KEY
2019-10-03 00:42:20 INFO (MainThread) [homeassistant.components.discovery] Found new service: samsung_tv {'host': '192.168.1.99', 'port': 7676, 'ssdp_description': 'http://192.168.1.99:7676/rcr/', 'name': 'Samsung 6 Series (40)', 'model_name': 'UE40KU6020', 'model_number': '1.0', 'serial': '20090804RCR', 'manufacturer': 'Samsung Electronics', 'udn': 'uuid:e79f4492-d0c5-4530-bd5a-75fcb7268fe2', 'upnp_device_type': 'urn:samsung.com:device:RemoteControlReceiver:1'}
2019-10-03 00:42:20 INFO (MainThread) [homeassistant.components.discovery] Unknown service discovered: home_assistant {'host': '192.168.1.200', 'port': 8123, 'hostname': 'Casa._home-assistant._tcp.local.', 'properties': {'version': '0.99.3', 'base_url': 'https://hapmst.duckdns.org:8123', 'requires_api_password': True}}
2019-10-03 00:42:20 INFO (MainThread) [homeassistant.components.discovery] Unknown service discovered: spotify_connect {'host': '172.30.33.2', 'port': 39629, 'hostname': 'a0d7b954-spotify.local.hass.io.local.', 'properties': {'VERSION': '1.0', 'CPath': '/'}}
2019-10-03 00:42:20 INFO (MainThread) [homeassistant.components.discovery] Unknown service discovered: dlna_dmr {'host': '192.168.1.99', 'port': 9197, 'ssdp_description': 'http://192.168.1.99:9197/dmr', 'name': '[TV] Samsung 6 Series (40)', 'model_name': 'UE40KU6020', 'model_number': 'AllShare1.0', 'serial': '0CU93HEH900133K', 'manufacturer': 'Samsung Electronics', 'udn': 'uuid:4219ca63-9d88-4f29-9312-63f881160257', 'upnp_device_type': 'urn:schemas-upnp-org:device:MediaRenderer:1'}
2019-10-03 00:42:20 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.samsungtv
2019-10-03 00:42:20 INFO (SyncWorker_2) [homeassistant.components.samsungtv.media_player] Ignoring duplicate Samsung TV 192.168.1.99:55000
2019-10-03 00:42:21 INFO (SyncWorker_16) [homeassistant.loader] Loaded smhi from homeassistant.components.smhi
2019-10-03 00:42:23 INFO (SyncWorker_1) [homeassistant.loader] Loaded traccar from homeassistant.components.traccar
2019-10-03 00:42:23 INFO (SyncWorker_1) [homeassistant.loader] Loaded zha from homeassistant.components.zha
2019-10-03 00:42:24 INFO (SyncWorker_5) [homeassistant.loader] Loaded geofency from homeassistant.components.geofency
2019-10-03 00:42:24 INFO (SyncWorker_8) [homeassistant.loader] Loaded notion from homeassistant.components.notion
2019-10-03 00:42:24 INFO (SyncWorker_1) [homeassistant.loader] Loaded wemo from homeassistant.components.wemo
2019-10-03 00:42:24 INFO (SyncWorker_0) [homeassistant.loader] Loaded ifttt from homeassistant.components.ifttt
2019-10-03 00:42:25 INFO (SyncWorker_9) [homeassistant.loader] Loaded iqvia from homeassistant.components.iqvia
2019-10-03 00:42:25 INFO (SyncWorker_8) [homeassistant.loader] Loaded cast from homeassistant.components.cast
2019-10-03 00:42:25 INFO (SyncWorker_5) [homeassistant.loader] Loaded tellduslive from homeassistant.components.tellduslive
2019-10-03 00:42:25 INFO (SyncWorker_7) [homeassistant.loader] Loaded ps4 from homeassistant.components.ps4
2019-10-03 00:42:25 INFO (SyncWorker_15) [homeassistant.loader] Loaded mailgun from homeassistant.components.mailgun
2019-10-03 00:42:25 INFO (SyncWorker_9) [homeassistant.loader] Loaded logi_circle from homeassistant.components.logi_circle
2019-10-03 00:42:26 INFO (SyncWorker_14) [homeassistant.loader] Loaded daikin from homeassistant.components.daikin
2019-10-03 00:42:26 INFO (SyncWorker_14) [homeassistant.loader] Loaded wwlln from homeassistant.components.wwlln
2019-10-03 00:42:26 INFO (SyncWorker_1) [homeassistant.loader] Loaded met from homeassistant.components.met
2019-10-03 00:42:26 INFO (SyncWorker_2) [homeassistant.loader] Loaded dialogflow from homeassistant.components.dialogflow
2019-10-03 00:42:26 INFO (SyncWorker_0) [homeassistant.loader] Loaded gpslogger from homeassistant.components.gpslogger
2019-10-03 00:42:26 INFO (SyncWorker_7) [homeassistant.loader] Loaded lifx from homeassistant.components.lifx
2019-10-03 00:42:26 INFO (SyncWorker_17) [homeassistant.loader] Loaded withings from homeassistant.components.withings
2019-10-03 00:42:26 INFO (SyncWorker_3) [homeassistant.loader] Loaded adguard from homeassistant.components.adguard
2019-10-03 00:42:26 INFO (SyncWorker_16) [homeassistant.loader] Loaded somfy from homeassistant.components.somfy
2019-10-03 00:42:26 INFO (SyncWorker_9) [homeassistant.loader] Loaded ios from homeassistant.components.ios
2019-10-03 00:42:26 INFO (SyncWorker_8) [homeassistant.loader] Loaded emulated_roku from homeassistant.components.emulated_roku
2019-10-03 00:42:26 INFO (SyncWorker_12) [homeassistant.loader] Loaded tplink from homeassistant.components.tplink
2019-10-03 00:42:26 INFO (SyncWorker_5) [homeassistant.loader] Loaded hue from homeassistant.components.hue
2019-10-03 00:42:26 INFO (SyncWorker_4) [homeassistant.loader] Loaded unifi from homeassistant.components.unifi
2019-10-03 00:42:26 INFO (SyncWorker_0) [homeassistant.loader] Loaded zwave from homeassistant.components.zwave
2019-10-03 00:42:26 INFO (SyncWorker_7) [homeassistant.loader] Loaded smartthings from homeassistant.components.smartthings
2019-10-03 00:42:26 INFO (SyncWorker_17) [homeassistant.loader] Loaded openuv from homeassistant.components.openuv
2019-10-03 00:42:26 INFO (SyncWorker_3) [homeassistant.loader] Loaded plaato from homeassistant.components.plaato
2019-10-03 00:42:26 INFO (SyncWorker_16) [homeassistant.loader] Loaded luftdaten from homeassistant.components.luftdaten
2019-10-03 00:42:26 INFO (SyncWorker_13) [homeassistant.loader] Loaded nest from homeassistant.components.nest
2019-10-03 00:42:26 INFO (SyncWorker_14) [homeassistant.loader] Loaded rainmachine from homeassistant.components.rainmachine
2019-10-03 00:42:26 INFO (SyncWorker_1) [homeassistant.loader] Loaded vesync from homeassistant.components.vesync
2019-10-03 00:42:26 INFO (SyncWorker_2) [homeassistant.loader] Loaded twilio from homeassistant.components.twilio
2019-10-03 00:42:26 INFO (SyncWorker_18) [homeassistant.loader] Loaded axis from homeassistant.components.axis
2019-10-03 00:42:26 INFO (SyncWorker_10) [homeassistant.loader] Loaded tradfri from homeassistant.components.tradfri
2019-10-03 00:42:26 INFO (SyncWorker_19) [homeassistant.loader] Loaded cert_expiry from homeassistant.components.cert_expiry
2019-10-03 00:42:26 INFO (SyncWorker_15) [homeassistant.loader] Loaded sonos from homeassistant.components.sonos
2019-10-03 00:42:26 INFO (SyncWorker_6) [homeassistant.loader] Loaded ambiclimate from homeassistant.components.ambiclimate
2019-10-03 00:42:26 INFO (SyncWorker_11) [homeassistant.loader] Loaded heos from homeassistant.components.heos
2019-10-03 00:42:26 INFO (SyncWorker_9) [homeassistant.loader] Loaded esphome from homeassistant.components.esphome
2019-10-03 00:42:26 INFO (SyncWorker_8) [homeassistant.loader] Loaded twentemilieu from homeassistant.components.twentemilieu
2019-10-03 00:42:26 INFO (SyncWorker_12) [homeassistant.loader] Loaded geonetnz_quakes from homeassistant.components.geonetnz_quakes
2019-10-03 00:42:26 INFO (SyncWorker_5) [homeassistant.loader] Loaded velbus from homeassistant.components.velbus
2019-10-03 00:42:26 INFO (SyncWorker_4) [homeassistant.loader] Loaded zone from homeassistant.components.zone
2019-10-03 00:42:26 INFO (SyncWorker_0) [homeassistant.loader] Loaded homematicip_cloud from homeassistant.components.homematicip_cloud
2019-10-03 00:42:26 INFO (SyncWorker_7) [homeassistant.loader] Loaded deconz from homeassistant.components.deconz
2019-10-03 00:42:26 INFO (SyncWorker_17) [homeassistant.loader] Loaded solaredge from homeassistant.components.solaredge
2019-10-03 00:42:26 INFO (SyncWorker_3) [homeassistant.loader] Loaded life360 from homeassistant.components.life360
2019-10-03 00:42:26 INFO (SyncWorker_16) [homeassistant.loader] Loaded ambient_station from homeassistant.components.ambient_station
2019-10-03 00:42:26 INFO (SyncWorker_13) [homeassistant.loader] Loaded toon from homeassistant.components.toon
2019-10-03 00:42:26 INFO (SyncWorker_14) [homeassistant.loader] Loaded linky from homeassistant.components.linky
2019-10-03 00:42:26 INFO (SyncWorker_1) [homeassistant.loader] Loaded owntracks from homeassistant.components.owntracks
2019-10-03 00:42:26 INFO (SyncWorker_2) [homeassistant.loader] Loaded point from homeassistant.components.point
2019-10-03 00:42:26 INFO (SyncWorker_18) [homeassistant.loader] Loaded simplisafe from homeassistant.components.simplisafe
2019-10-03 00:42:26 INFO (SyncWorker_10) [homeassistant.loader] Loaded hangouts from homeassistant.components.hangouts
2019-10-03 00:42:26 INFO (SyncWorker_19) [homeassistant.loader] Loaded iaqualink from homeassistant.components.iaqualink
2019-10-03 00:42:26 INFO (SyncWorker_15) [homeassistant.loader] Loaded locative from homeassistant.components.locative
2019-10-03 00:42:27 INFO (SyncWorker_9) [root] Sending control command: KEY
2019-10-03 00:42:38 INFO (SyncWorker_16) [root] Sending control command: KEY
2019-10-03 00:42:49 INFO (SyncWorker_5) [root] Sending control command: KEY
2019-10-03 00:43:00 INFO (SyncWorker_15) [root] Sending control command: KEY
core-ssh:~#

**Comment by zeputt** [comment] 2019-10-04 08:51
I have the same issue.
Installed from HACS and shelly: in configuration but no devices at all.

This is what is shown in logs regarding shelly:

2019-10-04 09:36:41 INFO (MainThread) [homeassistant.setup] Setting up shelly,
2019-10-04 09:36:41 INFO (SyncWorker_6) [custom_components.shelly] Starting shelly, 0.1.0,
2019-10-04 09:36:41 INFO (SyncWorker_6) [pyShelly] Init pyShelly 0.1.0,
2019-10-04 09:36:41 INFO (SyncWorker_6) [custom_components.shelly] pyShelly, 0.1.0

**Comment by hakana** [comment] 2019-10-04 10:23
> I have the same issue.
> Installed from HACS and shelly: in configuration but no devices at all.
> 
> This is what is shown in logs regarding shelly:
> 
> 2019-10-04 09:36:41 INFO (MainThread) [homeassistant.setup] Setting up shelly,
> 2019-10-04 09:36:41 INFO (SyncWorker_6) [custom_components.shelly] Starting shelly, 0.1.0,
> 2019-10-04 09:36:41 INFO (SyncWorker_6) [pyShelly] Init pyShelly 0.1.0,
> 2019-10-04 09:36:41 INFO (SyncWorker_6) [custom_components.shelly] pyShelly, 0.1.0

See other issues, this is about seeing some of the units, not none. There is other issues reported for that and it is because your network not is configured or support multicasts.

**Comment by zeputt** [comment] 2019-10-04 14:58
> 
> 
> > I have the same issue.
> > Installed from HACS and shelly: in configuration but no devices at all.
> > This is what is shown in logs regarding shelly:
> > 2019-10-04 09:36:41 INFO (MainThread) [homeassistant.setup] Setting up shelly,
> > 2019-10-04 09:36:41 INFO (SyncWorker_6) [custom_components.shelly] Starting shelly, 0.1.0,
> > 2019-10-04 09:36:41 INFO (SyncWorker_6) [pyShelly] Init pyShelly 0.1.0,
> > 2019-10-04 09:36:41 INFO (SyncWorker_6) [custom_components.shelly] pyShelly, 0.1.0
> 
> See other issues, this is about seeing some of the units, not none. There is other issues reported for that and it is because your network not is configured or support multicasts.

Ahh, ok.
I got it sorted with running my docker instance with HOST network instead.

**Comment by uaparac** [comment] 2019-10-05 14:23
After reinstall plug-in from HACS
Entities appear in the Unused Entities zone but devices appear as unavailable.

**Comment by rufik** [comment] 2019-11-23 15:02
HACS shows v0.1.0 onloy, while v0.1.3 has been released.
For proper "integration" with HACS this guide should be fine: https://hacs.xyz/docs/publish/start

**Comment by hakana** [comment] 2019-11-23 20:45
Sorry, the readme was updated to 0.1.3 by mistake. 0.1.0 is the latest release, 0.1.3 is released in beta 1. You need to enable beta in HACS to see it.

**Comment by Kedryn** [comment] 2019-12-10 23:39
I can't find how to enable betas in HACS

**Comment by hakana** [comment] 2019-12-11 07:18
You do that for each component in the hamburger menu.

**Comment by chemelli74** [comment] 2020-01-22 07:15
@uaparac , @Kedryn can you retest with 0.1.6b7 and latest firmare ?

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-01-30 14:59
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-02-12 22:22
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-02-12 22:22 UTC
Labels: question
