### ISSUE TITLE
Random Unavaible

### ISSUE THREAD

**Issue by Vitosant** [StyraHem/ShellyForHASS#268] opened 2020-04-16 10:04 UTC
Shellys often go into unavailable. I have tested the 2.5 that a plugs.
![unavaible](https://user-images.githubusercontent.com/62880910/79443586-4c6c8580-7fda-11ea-959b-914a14662269.JPG)

**Comment by fitim7** [comment] 2020-04-16 10:43
I also have this issue. I've noticed this behavior since I had to turn mDNS off because of https://github.com/StyraHem/ShellyForHASS/issues/267

**Comment by hakana** [comment] 2020-04-16 10:56
Try igmp fix option

**Comment by chemelli74** [comment] 2020-04-16 12:02
Please check also uptime trough http://<device ip>/status.

Simone

**Comment by chemelli74** [comment] 2020-04-23 06:59
Hi all, just to inform that after 3 weeks of inactivities on thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-05-01 14:35
Please update to latest beta (0.1.8.b2) and report back.

Simone

**Comment by chemelli74** [comment] 2020-05-09 22:38
No update for 21 days, closing

Simone

**Closed** 2020-05-09 22:38 UTC
Labels: support
