### ISSUE TITLE
[BUG] shelly flood update (rain mode)

### ISSUE THREAD

**Issue by mironalessandro** [StyraHem/ShellyForHASS#337] opened 2020-06-28 10:57 UTC
## Environment

- ShellyForHASS release with the issue: 
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 
- Operating environment (Home Assistant/Supervised/Docker/venv): 

## Describe the bug

Problem with Shelly flood with rain mode. I see the changes in HA only on the change of rain mode and not on temperature change.

## Steps to Reproduce

No configuration. After adding flood device in shelly app in RAIN MODE I can see the entity on HA. But there are no updates. The updates are maybe after some days. very randomly. All the other device works properly.

## Expected behavior

I expect the updates when I see the updates on shelly app.

## Screenshots

![image](https://user-images.githubusercontent.com/54042200/86369541-e14c5a00-bc7e-11ea-8514-f1cd97559390.png)

![image](https://user-images.githubusercontent.com/54042200/86370530-2755ed80-bc80-11ea-964a-8c25f287443d.png)

## Traceback/Error logs

```txt

```
2020-06-30 01:18:02 WARNING (MainThread) [homeassistant.components.switch] SwitchDevice is deprecated, modify ShellySwitch to extend SwitchEntity
2020-06-30 01:18:02 WARNING (MainThread) [homeassistant.components.switch] SwitchDevice is deprecated, modify ShellyFirmwareUpdate to extend SwitchEntity
2020-06-30 01:18:02 WARNING (MainThread) [homeassistant.components.light] Light is deprecated, modify ShellyLightRelay to extend LightEntity
2020-06-30 01:18:02 WARNING (MainThread) [homeassistant.components.light] Light is deprecated, modify ShellyDimmer to extend LightEntity
2020-06-30 01:18:02 WARNING (MainThread) [homeassistant.components.light] Light is deprecated, modify ShellyRGB to extend LightEntity
2020-06-30 01:18:02 WARNING (MainThread) [homeassistant.components.binary_sensor] BinarySensorDevice is deprecated, modify ShellySwitch to extend BinarySensorEntity
2020-06-30 01:18:02 WARNING (MainThread) [homeassistant.components.binary_sensor] BinarySensorDevice is deprecated, modify ShellyBinarySensor to extend BinarySensorEntity
2020-06-30 01:18:02 WARNING (MainThread) [homeassistant.components.binary_sensor] BinarySensorDevice is deprecated, modify ShellyBinaryInfoSensor to extend BinarySensorEntity
2020-06-30 01:18:03 WARNING (MainThread) [homeassistant.components.cover] CoverDevice is deprecated, modify ShellyCover to extend CoverEntity
## Additional context

I don't know if these errors can be associated with shellyforhass

**Comment by chemelli74** [comment] 2020-06-28 11:26
Please fill the template.

Simone

**Comment by chemelli74** [comment] 2020-07-02 12:54
Looking for the updated template.
Otherwise I'll have to close this issue.

Simone

**Comment by mironalessandro** [comment] 2020-07-02 13:20
Tell me if I can help you with test or logs.
Thanks

**Comment by chemelli74** [comment] 2020-07-02 13:29
> Tell me if I can help you with test or logs.
> Thanks

First you have to fulfill the issue template.

Simone

**Comment by mironalessandro** [comment] 2020-07-02 14:19
> > Tell me if I can help you with test or logs.
> > Thanks
> 
> First you have to fulfill the issue template.
> 
> Simone

Here you are

**Comment by chemelli74** [comment] 2020-07-02 18:00
You still miss the first part of the template, the environment.

Anyway, I can see from the log that you are on 0.1.8.
Please update to 0.19.b1 are report back.

Simone

**Comment by mironalessandro** [comment] 2020-07-02 18:07
> You still miss the first part of the template, the environment.
> 
> 
> 
> Anyway, I can see from the log that you are on 0.1.8.
> 
> Please update to 0.19.b1 are report back.
> 
> 
> 
> Simone

Sorry! 

Yes confirm 1.8 and Hassio 111.4 but I cannot see it in hacs.. 1.9 is a beta version what I need to do to have it?

**Comment by chemelli74** [comment] 2020-07-03 08:38
> Yes confirm 1.8 and Hassio 111.4 but I cannot see it in hacs.. 1.9 is a beta version what I need to do to have it?

Enable beta in HACS ;-)

Simone

**Comment by mironalessandro** [comment] 2020-07-03 18:32
> > Yes confirm 1.8 and Hassio 111.4 but I cannot see it in hacs.. 1.9 is a beta version what I need to do to have it?
> 
> 
> 
> Enable beta in HACS ;-)
> 
> 
> 
> Simone

Thanks 
Any eta for the official one?

**Comment by chemelli74** [comment] 2020-07-27 06:50
Please report back is using 0.1.9 is working as expected.

Simone

**Comment by chemelli74** [comment] 2020-08-01 12:42
Hi all, just to inform that after 3 weeks of inactivity on thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Closed** 2022-11-05 13:03 UTC
Labels: support, waiting for feedback
