### ISSUE TITLE
[BUG] Roller Shutter multiple entries in HA logbook

### ISSUE THREAD

**Issue by denniswham** [StyraHem/ShellyForHASS#325] opened 2020-06-16 08:55 UTC
## Environment

- ShellyForHASS release with the issue: 0.1.9.beta.2
- Last working ShellyForHASS release (if known): not known
- Home Assistant Core release with the issue: 0.111.3
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant

## Describe the bug

When closing or opening a roller shutter, I see multiple confusing states in the HA logbook. I have this for all three roller shutters.

## Steps to Reproduce
Close a roller Shutter from 100 -> 0 %
Opening a roller shutter from 0 -> 100%
Check the log

## Expected behavior

When closing, see one entry with state "closing", followed by an entry with state "closed"
When opening, see one entry with state "opening", followed by an entry  with state "opened"

## Screenshots

![image](https://user-images.githubusercontent.com/43110823/84753503-5c471c80-afbf-11ea-9f19-9969d1f220ae.png)

## Traceback/Error logs

```txt

```

**Comment by chemelli74** [comment] 2020-08-17 22:33
Unable to reproduce with firmware 1.7, HA 0.114.1 and ShellyForHASS 0.1.9.b3

Simone

**Comment by chemelli74** [comment] 2020-08-28 21:05
No updated info provided, closing.

Simone

**Closed by chemelli74** 2020-08-28 21:05 UTC
Labels: help wanted
