### ISSUE TITLE
Uncalibrated Shelly 2.5 in Rollershutter mode doesn’t work correctly

### ISSUE THREAD

**Issue by GrtDlks** [StyraHem/ShellyForHASS#25] opened 2019-06-02 19:22 UTC
When a Shelly 2.5 in Rollershutter mode isn’t calibrated, the up and down buttons won’t work 
At the moment:
![33F84EE0-E257-4953-B44A-2D03821173B0](https://user-images.githubusercontent.com/7464464/58766221-4c0efb80-857c-11e9-8b7b-3ffedd82a2da.jpeg)

Should be:
![17FD336A-3693-47C2-8A6A-84E07F5FF30E](https://user-images.githubusercontent.com/7464464/58766222-4c0efb80-857c-11e9-826b-c8efde87b691.jpeg)

**Comment by hakana** [comment] 2019-06-14 14:35
I will have a look on that to next release.

**Comment by Senbei123** [comment] 2019-07-08 19:48
I also have this issue.

**Comment by hakana** [comment] 2019-08-21 22:13
I can't reproduce this. When I'm trying it working as it should. What happen if you click on the arrow or change it in the Shelly app?

**Comment by sentinel43** [comment] 2019-09-20 21:29
I can confirm this issue. If you click on the greyed arrow, pop up window will come up like when you miss the button. I tried mine over shelly app and it works fine. Sa me is over the switch. I noticed that when shutter is full opened, down icon in hassio is greyed and I cant click it to close. As soon I click it on physical switch and move it down a little bit than down arrow in hassio is black and I can close it further but arrow for up is greyed out. It seems that over hassio you can move it just in the same direction like last one you used over the switch or shelly app.

**Comment by hakana** [comment] 2019-09-20 21:32
I will check that later, for the moment I only hava a calibrated 2.5. Why are you not calibrating yours?

**Comment by Senbei123** [comment] 2019-09-21 07:09
Hi, I calibrate the 2.5 and close it to 20%. But the button for UP is still gray... :(

**Comment by Senbei123** [comment] 2019-09-21 07:18
Okay. I did a Firmware update on the shelly and now a position line is shown in home assistant. BUT when you choose the shelly app to put the roller to eg 80%, home assistant don't get this "status update". It still is on 100% open - button grey. 
Only when it is completely used within home assistant (your component) then it works fine.

**Comment by hakana** [comment] 2019-09-21 14:25
Can you do a http://shelly-ip/status and http://shelly-ip/settings and post here. Please replace if there are any sensitive information like password etc.

**Comment by chemelli74** [comment] 2020-01-22 07:10
@GrtDlks, @Senbei123 can you retest with 0.1.6b7 and latest firmware ?

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-01-30 14:56
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-02-12 22:21
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-02-12 22:21 UTC
Labels: bug, question
