### ISSUE TITLE
Doesn't show power consumption from Shelly 1 PM 

### ISSUE THREAD

**Issue by gufi666** [StyraHem/ShellyForHASS#98] opened 2019-11-13 16:10 UTC
Hello,

I install plugin and there is now consumption from Shelly 1 PM. From Shelly 2,5 there is no problem works fine. Any ideas to resolve this problem  ???? 

BR 
Artur

**Comment by drlimbo** [comment] 2019-11-15 14:04
Looks like this isn't supported as mentioned [here](https://github.com/StyraHem/ShellyForHASS#devices-supported)
> Shelly 1 PM (no power meter, firmware bug)

That's sad because the [Shelly Button](https://shelly.cloud/smart-wifi-home-automation-shelly-button/) only supports Shelly1 and Shelly1PM. So there's no way to create a "smart cable" with Shelly Button including a Power Meter (Shelly1PM only). 

Maybe this could be fixed some day by @hakana ?

**Comment by hakana** [comment] 2019-11-19 22:45
Please, try latest release! Also join FB gropup for updates: https://www.facebook.com/groups/shellyforhass/

**Comment by Kedryn** [comment] 2019-12-02 14:24
I can confirm that in 0.1.3 there is still no total power in shelly 1 PM.

**Comment by chemelli74** [comment] 2020-01-22 07:20
Hi @Kedryn, can you retest with 0.1.6b7 and update to latest firmware 1.5.8 as well ?

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-01-30 15:03
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-02-12 22:24
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-02-12 22:24 UTC
Labels: question
