### ISSUE TITLE
[BUG] on new version

### ISSUE THREAD

**Issue by milandzuris** [StyraHem/ShellyForHASS#710] opened 2022-09-02 16:41 UTC
## Environment

- ShellyForHASS release with the issue: 
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 
- Operating environment (Home Assistant/Supervised/Docker/venv): 

## Screenshots
![image](https://user-images.githubusercontent.com/42905545/188199790-59d6f69d-ee7c-4030-913f-65458086e47e.png)

## Traceback/Error logs
Logger: homeassistant.setup
Source: setup.py:320
First occurred: 18:03:58 (1 occurrences)
Last logged: 18:03:58

Unable to prepare setup for platform shelly.light: Platform not found (cannot import name 'ATTR_WHITE_VALUE' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)).

## Additional context
version core 22.9.**

**Comment by mattlamb99** [comment] 2022-09-07 21:45
Duplicate of #713

**Closed** 2022-09-13 03:23 UTC
