### ISSUE TITLE
How to keep Devices to avoid HomeKit issues

### ISSUE THREAD

**Issue by vistalba** [StyraHem/ShellyForHASS#128] opened 2019-12-24 10:33 UTC
Good Morning

May this is a stupid question but I didn't find a answer until now.

I run some Shelly H&T (on battery) which reports temperature, humidity and battery to homeassistant.
After every reboot of HA the entities are gone. Then I've to wait until the Shelly H&T comes next time back online to report values. Sometimes this could take 12h.

The problem I now have with HomeKit is, that only devices are reportet to HomeKit that exists BEFORE HomeKit has startet.

So at the moment I've an automation that starts HomeKit 5min after HA. This is not enough for shelly H&T. But I don't want to wait 12h before restart. So best would be to be able to "save" some devices that are configured in `shelly:`.

Any solution for that?

**Comment by vistalba** [comment] 2019-12-27 13:13
There should be a way to keep the H&T entity (if desired as configuration) and cache the latest value of the sensor so provide it to HomeAssistant.

Is this possible?

**Comment by chemelli74** [comment] 2020-01-21 10:25
@vistalba , please test with HA >= 0.104.0 as there entities are now cached.

Simone

**Comment by chemelli74** [comment] 2020-01-30 15:14
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by vistalba** [comment] 2020-01-30 16:43
For me it looks much better now.

**Comment by chemelli74** [comment] 2020-02-05 07:31
Hi,

can you please close the issue ?

Simone

**Closed** 2020-02-05 07:49 UTC
Labels: enhancement
