### ISSUE TITLE
Slow update of lovelace card (CoAP not working)

### ISSUE THREAD

**Issue by fpalinf** [StyraHem/ShellyForHASS#158] opened 2020-01-19 18:42 UTC
Hello,

With all the shelly switch I use (light, 2.5, led) when I switch on or off the shelly actually switches but the update of the visual indication on lovelace takes sometimes 1 minute.

I would be happy to provide debug log if of any help.

**Comment by chemelli74** [comment] 2020-01-21 08:04
@fpalinf , please report back which version of the plugin you are using and attach the debug log. Also take a screenshot of the device details in lovelace (the card that open when you click on it).

Thank you,

Simone

**Comment by fpalinf** [comment] 2020-01-21 09:08
Plugin version: 0.1.5 (the newest in HACS)
Where can I find the debug logs ?

It actually always update but it is not instantenously.
All card using a shelly updates together at the same time regardless when they were activated. 
It seems like a batch update. 

Object linked with MQTT or  - platform: flux_led update instantenously.

<img width="359" alt="Screenshot 2020-01-21 at 09 58 42" src="https://user-images.githubusercontent.com/19511928/72790105-38142900-3c35-11ea-8b0c-a7998aba3e16.png">

**Comment by chemelli74** [comment] 2020-01-21 10:15
Hi,

I see you did a discovery by IP-address.
Would be possible to do a automatic discovery using CoAP ?
IIRC this is the only way to get istantaneous update, otherwise update is a polling every 60 seconds.

To actrivate debug log you have to add those lines to configuration.yaml:

```
logger:                                                                                                                                                                                                     
  default: warn                                                                                                                                                                                             
  logs:                                                                                                                                                                                                     
      **pyShelly: debug**                                                                                                                                                                                       

```
Log file is "home-assistant.log" in your config folder
               
Simone

**Comment by fpalinf** [comment] 2020-01-21 12:04
Ok, I manage to setup logs thank you.

Without discovery IP-addr the devices are found by mDNS. No shelly are discovered by CoAP.
If CoAP is the only way to have instantaneous update then I will investigate the network issue.

To give you more insight: 
My hassio is running in docker on ubuntu alongside other containers.
The ubuntu runs on a machine with two interfaces with an ip addr on each if (wan and lan)
When CoAP discorvery only one device is answering (the machine but with the wan ip)

**Comment by fpalinf** [comment] 2020-01-21 12:08
In parralel, wouldn't it be possible to use CoAP for the shelly without the automatic CoAP discovery ?

**Comment by hakana** [comment] 2020-01-21 21:49
You can try to install the latest beta (6) and set the parameter host_ip and see if that helps to get CoAP to work.
```yaml
shelly:
  host_ip: 192.168.xxx.yyy
```

**Comment by fpalinf** [comment] 2020-01-21 22:42
I just switched to master beta 7 and add host_ip
Major improvement in shellies speed detection.
Shellies are now: discovery CoAP-discovery

But still the problem is there:
Light is ON, Card is ON.
I press the card and the card goes OFF and the light goes OFF.
```
2020-01-21 23:37:59 DEBUG (SyncWorker_5) [pyShelly] http://10.90.1.70/color/0?turn=off
2020-01-21 23:37:59 DEBUG (SyncWorker_5) [pyShelly] http://10.90.1.70/color/0?turn=off - Ok

```

But the card immediately goes back ON

Till the next poll check:
```
2020-01-21 23:38:23 INFO (Thread-43) [pyShelly] Get status from B0390C Shelly RGBW2 - B0390C
2020-01-21 23:38:23 DEBUG (Thread-43) [pyShelly] http://10.90.1.70/status
2020-01-21 23:38:23 DEBUG (Thread-43) [pyShelly] http://10.90.1.70/status - Ok
2020-01-21 23:38:23 INFO (Thread-43) [pyShelly] Update id:B0390C state:False stateValue:{'mode': 'color', 'brightness': 100, 'rgb': [255, 255, 255], 'temp': 0, 'white_value': 255, 'effect': 0} values:None info_values:None
```
Then card goes back OFF (which is the correct state of the light)

**Comment by Misiu** [comment] 2020-01-22 07:40
> You can try to install the latest beta (6) and set the parameter host_ip and see if that helps to get CoAP to work.
> 
> ```yaml
> shelly:
>   host_ip: 192.168.xxx.yyy
> ```
So host IP is my Home Assistant IP, not my router IP? Just asking to be sure.

**Comment by hakana** [comment] 2020-01-22 07:42
Yes it is the HA's IP, it is used to select the interface of the device if it is multiple.

**Comment by dodg3r** [comment] 2020-01-22 17:41
Hi.

@fpalinf, Is your problem like this ?

The left window is my prod hassio and the right window is my fresh install of a dev instance.

https://1drv.ms/v/s!AgZRSIF72Mnv5W6_-lcOemSxaISx?e=UrIRI4

**Comment by fpalinf** [comment] 2020-01-22 18:30
Hi @dodg3r Yes exactly.

**Comment by dodg3r** [comment] 2020-01-22 19:30
Do you use slider-entity-row addon to entities cards ?

**Comment by fpalinf** [comment] 2020-01-22 20:17
@dodg3r No I do not.
What is the difference between your prod and dev installation ?

**Comment by dodg3r** [comment] 2020-01-23 07:16
Hi.
A stupid question. 
Have you tried to restart your computer ? Not just hass..

My dev installation is a fresh install with only hacs and shelly for hass installed.
I will try to explain. I´m from Sweden and my english isnt that good so I hope you understand.

From the beginning:
Months ago I replaced my rasp with at hp proliant server with linux and docker.
I only used z-wave devices and everything worked like a charm :)
But then this problem accoured and I thought that it was a z-wave problem.
I replaced all of my 30 devices with shelly :) and made a new fresh installation from the beginning. No restoring from backups.
All worked well but then all of a sudden the same problem was back :(
I suspected that it maybe had something to do with the addon slider-entity-row that I´ve installed just before the lags occured.
I unistalled it and restarted and the lags was gone.
The strange thing is that now I reinstalled the addon but the lags is still gone :( 
So I dont know what to think ?

**Comment by fpalinf** [comment] 2020-01-24 10:09
@dodg3r Maybe you should raise this issue on Hass then with your video. By reading your story I am not sure it is related to ShellyForHASS

**Comment by fpalinf** [comment] 2020-01-24 10:15
Anybody have an idea on how I could investigate more on this issue ?

**Comment by dodg3r** [comment] 2020-01-24 10:18
Did you do a restart of your computer :)

**Comment by chemelli74** [comment] 2020-01-24 13:45
Seems you all agree that the issue is not in ShellyforHASS.
@dodg3r can you install a "dev" environment, so a clean installation of HA > 104.0 and latest beta8 fro ShellyForHASS and report back ?

Simone

**Comment by dodg3r** [comment] 2020-01-24 13:53
Hi.

I did a fresh install on my newly bought rasp 4 yesterday with hassio 104.3 and shellyforhass beta8 and everything works.
The reason I commented here is because I had the exact same problem with my zwave devices.
So in my oppinion I think there is something else in the setup making these lags.

But I might be wrong.

**Comment by geronimo078** [comment] 2020-01-28 07:48
I have exactly the same problem. Also tried to add the host_ip but this had no effect.
Beside shelly i use only Hue and Lifx on Home assistant and they are working perfectly.

**Comment by juanmm90** [comment] 2020-01-30 23:37
Hi,
I have the same issue in my Hass. :(

**Comment by jandrop** [comment] 2020-01-31 08:45
I have the same issue, coap discovery is working but the updates are between 60 seconds 

![image](https://user-images.githubusercontent.com/8020875/73524893-5be22680-440e-11ea-88fa-2027246f1818.png)

**Comment by paolograssi** [comment] 2020-02-02 22:30
I have the same problem.

Updated to Beta 9 with HA 0.104.3. CoAP discovered but still lot of delay with update.

I managed to reduce the update with scan_interval = 5 but from time to time I get weird behavior such as the light gets on but when switch is updated on HA to on it auto switch off.

Available for test, if needed.

**Comment by holdestmade** [comment] 2020-02-07 09:24
Same problem here, updated to Beta 10 with HA 0.105.1. Added host_ip and now CoAP discovered but still lot of delay with update of the status. Have MQTT running as well and they update instantly.

**Comment by paolograssi** [comment] 2020-02-07 20:23
Someone was able to get this working? I don't know if this is a router problem or so...

But with mqtt all working well? Dimming lights, rgb, etc... why not using mqtt instead for the library?

**Comment by Misiu** [comment] 2020-02-07 20:54
@paolograssi the answers is simple: if you want cloud (shelly app outside your Wi-Fi ) and home assistant you can't use MQTT. If you enable MQTT you loose cloud connection.

**Comment by hakana** [comment] 2020-02-07 22:17
The probably broadcast is not working in your network, check if you have a setting for igmp in your switch and routers that you can change.

**Comment by geronimo078** [comment] 2020-02-11 13:57
Tried to change the igmp setting on the router but the broadcast is still not working. The card update need about 30 seconds no matter what setting i use.
Meanwhile i changed one shelly to MQTT and this one works perfectly.

**Comment by kasteleman** [comment] 2020-02-11 14:01
Same here. Strang thing is that A wireshark scan on my pfsense box does not
show any coap traffic. Only http (80) and 5353. What am I missing?
Meanwhile changed the pollinterval to 5 sec in the config.

Op di 11 feb. 2020 om 14:57 schreef geronimo078 <notifications@github.com>

**Comment by emnik** [comment] 2020-02-16 22:37
Same problem here... Everything was working spontaneously until I changed router! After the change this happens :-(
I have tried all the above... CoAP-discovery works, the command is executed very very quickly but the lovelace button does not update for about a minute (sometimes less but quite long)
Before changing the router this had never happened.

**Comment by VaabenDK** [comment] 2020-02-22 18:35
I also experience problems with Shelly and COAP.
I'm running HassIO on a RPI so I expect Home Assistant is running in Docker?
After being thru all network settings in my Unifi network and doing a wireshark on another PC aside from Shelly and the RPI, I can see that all the multicast packages are on the network - both when connecting wired and wireless. I get a lot of COAP messages from the Shellies with consumption, statechanges, etc. - and ocassionaly a COAP from the RPI - I guess this is the discovery package. 

When looking in the HA logs, I can see it is using polling. When looking in the device section I can see SHellyforHass is using COAP discovery.

I have both the igmp_fix and the hiost_ip in configuration.yaml - and newest 1.16 version of shellyforhass

I suspect (like in #185) that the coap messages hit the RPI - but might be rejected or not sent to the right docker container.

**Comment by hakana** [comment] 2020-02-23 08:23
Try tcpdump in docker container and see if you can see the CoAP messages

**Comment by VaabenDK** [comment] 2020-02-23 09:11
I've installed the community ssh plugin in HA, then installed tcpdump. The only Ip adresses i saw is from 172.30.32.1 - no multicast messages or anything from my 192.168.2.0/24 subnet.
What I noticed now is that I get the quick response right after a restart of the RPI host. this could indicate that some other docker container starts up after hassio and maybe interrupts something?
I'll try later today to get a TCP dump running right after restart when I have the quick response and leave it running until it seems to switch to polling.

Which filters should I apply to TCP dump to only see COAP messages? Right now i try to filter for 224.0.1.187 which is the coap multicast address and also the RPI hosts own 192.168.x.x adress

**Comment by emnik** [comment] 2020-02-23 15:45
How come CoAP discovery works but CoAP update messages doesn't? What's so
different between them?
And a question that I've seen made many times but not answered yet. Is
there something else besides igmp proxy and igmp snooping enabled that we
can do in the router's configuration?

Στις Κυρ, 23 Φεβ 2020, 11:11 ο χρήστης VaabenDK <notifications@github.com>
έγραψε:

**Comment by VaabenDK** [comment] 2020-02-23 19:33
I discovered while testing that the slow updates (using polling) only happens when the dimmers is configured with inputs in "detached mode". As soon as I change them to actually control the dimmer directly, the reaction is instant.
I'll create seperate bug report for this as it is another issue

**Comment by chemelli74** [comment] 2020-02-23 19:49
> Tried to change the igmp setting on the router but the broadcast is still not working. The card update need about 30 seconds no matter what setting i use.

Debug log says what ? Polling ?

Simone

**Comment by chemelli74** [comment] 2020-02-23 19:52
> I just discovered while debugging and wiresharking that the issue I have is that the Shelly Dimmer must have a fw bug. When input are in detached mode, it takes many seconds from input is switched to the coap message is sent out. When the inputs directly controls the dimmer, the sending of coap msg is instant.
> 
> I'll file a bug with Shelly instead :)

Thx for the feedback. Please update this thread as soon as Dimitar give you a feedback.

Simone

**Comment by chemelli74** [comment] 2020-02-23 20:03
> How come CoAP discovery works but CoAP update messages doesn't? What's so different between them? And a question that I've seen made many times but not answered yet. Is there something else besides igmp proxy and igmp snooping enabled that we can do in the router's configuration?

Maybe you can enable debug log and see if those are received or not, and if yes if they are delayed or istant.

Simone

**Comment by emnik** [comment] 2020-02-23 22:05
using Wireshark at the Pi I get CoAP packages with:
```
Source = HA IP       Destination = 224.0.1.187    Info = GET, /cit/d
Source = Shely IP   Destination = HA IP Info = Content 
the responce content is like: ({"blk":[{"I":0,"D":"Relay0"},{"I":1,"D":"Sensors"}],"sen":[{"I":112,"T":"S","D":"Switch","R":"0/1","L":0},{"I":118,"T":"S","D":"Input","R":"0/1/2","L":1}]}
```
This is the discovery messages if I understand correct.

I don't get another type of CoAP messages and in the debug although I see: Discovery CoAP messages send and received I don't see any device status messages to be send.

Shouldn't a CoAP GET message in /cit/s to be send from HA like described in https://shelly-api-docs.shelly.cloud/#coiot ?

**Comment by chemelli74** [comment] 2020-02-23 22:18
Using "**tcpdump -A udp port 5683**":

`E....................3.3...IP..;.cit.s....SHSW-25#xxxxx#1.C......{"G":[[0,112,0],[0,122,0],[0,111,0.000000],[0,121,0.000000],[0,118,0],[0,128,2],[0,115,54.38],[0,116,129.88],[0,117,0]]}`

Simone

**Comment by emnik** [comment] 2020-02-24 13:23
```homeassistant@homeassistant:~$ tshark -i eth0 -f 'udp port 5683'
Capturing on 'eth0'
    1 0.000000000 192.168.0.50 → 224.0.1.187  CoAP 53 NON, MID:10, GET, /cit/d
    2 0.015707500 192.168.0.81 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
    3 0.016000104 192.168.0.80 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
    4 0.016207708 192.168.0.82 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
    5 0.046305312 192.168.0.84 → 192.168.0.50 CoAP 603 NON, MID:10, 2.05 Content
    6 0.060941250 192.168.0.83 → 192.168.0.50 CoAP 603 NON, MID:10, 2.05 Content
    7 33.393260456  192.168.0.7 → 224.0.1.187  CoAP 60 NON, MID:325, GET, /cit/s
    8 60.119136331 192.168.0.50 → 224.0.1.187  CoAP 53 NON, MID:10, GET, /cit/d
    9 60.152015029 192.168.0.81 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
   10 60.174631331 192.168.0.84 → 192.168.0.50 CoAP 603 NON, MID:10, 2.05 Content
   11 60.207357633 192.168.0.83 → 192.168.0.50 CoAP 603 NON, MID:10, 2.05 Content
   12 73.410588305  192.168.0.7 → 224.0.1.187  CoAP 60 NON, MID:326, GET, /cit/s
   13 120.224180996 192.168.0.50 → 224.0.1.187  CoAP 53 NON, MID:10, GET, /cit/d
   14 120.233444537 192.168.0.81 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
   15 120.238221673 192.168.0.82 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
   16 120.241650683 192.168.0.84 → 192.168.0.50 CoAP 603 NON, MID:10, 2.05 Content
   17 120.245114850 192.168.0.83 → 192.168.0.50 CoAP 603 NON, MID:10, 2.05 Content
   18 180.327889723 192.168.0.50 → 224.0.1.187  CoAP 53 NON, MID:10, GET, /cit/d
   19 180.341484618 192.168.0.82 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
   20 180.341886493 192.168.0.81 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
   21 180.342163525 192.168.0.80 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
   22 180.350055660 192.168.0.84 → 192.168.0.50 CoAP 603 NON, MID:10, 2.05 Content
   23 180.358541077 192.168.0.83 → 192.168.0.50 CoAP 603 NON, MID:10, 2.05 Content
   24 240.447544023 192.168.0.50 → 224.0.1.187  CoAP 53 NON, MID:10, GET, /cit/d
   25 240.470253971 192.168.0.82 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
   26 240.494633398 192.168.0.81 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
   27 240.578767564 192.168.0.84 → 192.168.0.50 CoAP 603 NON, MID:10, 2.05 Content
   28 240.601149335 192.168.0.83 → 192.168.0.50 CoAP 603 NON, MID:10, 2.05 Content
   29 240.606326627 192.168.0.80 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
   30 300.695364833 192.168.0.50 → 224.0.1.187  CoAP 53 NON, MID:10, GET, /cit/d
   31 300.706050093 192.168.0.81 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
   32 300.706505979 192.168.0.82 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
   33 300.707117229 192.168.0.80 → 192.168.0.50 CoAP 221 NON, MID:10, 2.05 Content
   34 300.720166291 192.168.0.84 → 192.168.0.50 CoAP 603 NON, MID:10, 2.05 Content
   35 300.736015718 192.168.0.83 → 192.168.0.50 CoAP 603 NON, MID:10, 2.05 Content
^C35 packets captured
```
The 192.168.0.8x are the Shellies
The 192.168.0.50 is the home assistant host
The 192.168.0.7 is my android phone with the Shelly app 
So shelly app does indeed issue a GET command to /cit/s but (for me) homeassistant doens't :-(

I can understand  CoAP packages might not reach HA but I can't understand why I don't see a GET command to /cit/s originating from HA. The same results I also get with tcpdump...

**Comment by chemelli74** [comment] 2020-02-24 13:46
Which flags you use on calling tcpdump ?
I run "**tcpdump -A udp port 5683**"

Output is:

```
14:42:43.601591 IP shellyswitch25-xxxxxx.5683 > 224.0.1.187.5683: UDP, length 168
E...J..........,.....3.3..ZHP....cit.s....SHSW-25#xxxxxx#1.C...Q..{"G":[[0,112,0],[0,122,0],[0,113,0],[0,111,0.000000],[0,121,0.000000],[0,118,0],[0,128,0],[0,115,52.47],[0,116,126.45],[0,117,0]]}
```

Simone

**Comment by emnik** [comment] 2020-02-25 10:21
this is what I get (repeatedly):
```
homeassistant@homeassistant:~/.homeassistant$ sudo tcpdump -A udp port 5683
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes

12:18:18.194049 IP 192.168.0.50.5683 > 224.0.1.187.5683: UDP, length 11
E..'..@.
..Z...2.....3.3....P..
.cit.d.
12:18:18.204029 IP 192.168.0.82.5683 > 192.168.0.50.5683: UDP, length 179
E....@.....     ...R...2.3.3....PE.
....SHSW-1#xxxxxx#1.{"blk":[{"I":0,"D":"Relay0"},{"I":1,"D":"Sensors"}],"sen":[{"I":112,"T":"S","D":"Switch","R":"0/1","L":0},{"I":118,"T":"S","D":"Input","R":"0/1/2","L":1}]}
12:18:18.204728 IP 192.168.0.81.5683 > 192.168.0.50.5683: UDP, length 179
E..........w...Q...2.3.3....PE.
....SHSW-1#xxxxxx#1.{"blk":[{"I":0,"D":"Relay0"},{"I":1,"D":"Sensors"}],"sen":[{"I":112,"T":"S","D":"Switch","R":"0/1","L":0},{"I":118,"T":"S","D":"Input","R":"0/1/2","L":1}]}
12:18:18.207423 IP 192.168.0.80.5683 > 192.168.0.50.5683: UDP, length 179
E....=.........P...2.3.3....PE.
....SHSW-1#xxxxxx#1.{"blk":[{"I":0,"D":"Relay0"},{"I":1,"D":"Sensors"}],"sen":[{"I":112,"T":"S","D":"Switch","R":"0/1","L":0},{"I":118,"T":"S","D":"Input","R":"0/1/2","L":1}]}
12:18:18.208503 IP 192.168.0.84.5683 > 192.168.0.50.5683: UDP, length 561
E..M...........T...2.3.3.9..PE.
....SHSW-25#xxxxxx#1.{"blk":[{"I":0,"D":"Relay0"},{"I":1,"D":"Relay1"},{"I":2,"D":"Device"}],"sen":[{"I":112,"T":"S","D":"State","R":"0/1","L":0},{"I":122,"T":"S","D":"State","R":"0/1","L":1},{"I":111,"T":"W","D":"Power","R":"0/2300","L":0},{"I":121,"T":"W","D":"Power","R":"0/2300","L":1},{"I":113,"T":"S","D":"Position","R":"0/100","L":2},{"I":118,"T":"S","D":"Input","R":"0/1/2","L":2},{"I":128,"T":"S","D":"Input","R":"0/1/2","L":2},{"I":115,"T":"tC","R":"-40/300","L":2},{"I":116,"T":"tF","R":"-40/300","L":2},{"I":117,"T":"Overtemp","R":"0/1","L":2}]}
12:18:18.226127 IP 192.168.0.83.5683 > 192.168.0.50.5683: UDP, length 561
E..M...........S...2.3.3.9..PE.
....SHSW-25#xxxxxx#1.{"blk":[{"I":0,"D":"Relay0"},{"I":1,"D":"Relay1"},{"I":2,"D":"Device"}],"sen":[{"I":112,"T":"S","D":"State","R":"0/1","L":0},{"I":122,"T":"S","D":"State","R":"0/1","L":1},{"I":111,"T":"W","D":"Power","R":"0/2300","L":0},{"I":121,"T":"W","D":"Power","R":"0/2300","L":1},{"I":113,"T":"S","D":"Position","R":"0/100","L":2},{"I":118,"T":"S","D":"Input","R":"0/1/2","L":2},{"I":128,"T":"S","D":"Input","R":"0/1/2","L":2},{"I":115,"T":"tC","R":"-40/300","L":2},{"I":116,"T":"tF","R":"-40/300","L":2},{"I":117,"T":"Overtemp","R":"0/1","L":2}]}

```

**Comment by chemelli74** [comment] 2020-02-25 12:54
> this is what I get (repeatedly):
> 
> ```
> homeassistant@homeassistant:~/.homeassistant$ sudo tcpdump -A udp port 5683
> tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
> listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
> 
> 12:18:18.194049 IP 192.168.0.50.5683 > 224.0.1.187.5683: UDP, length 11
> E..'..@.
> ..Z...2.....3.3....P..
> .cit.d.
> 12:18:18.204029 IP 192.168.0.82.5683 > 192.168.0.50.5683: UDP, length 179
> E....@.....     ...R...2.3.3....PE.
> ....SHSW-1#xxxxxx#1.{"blk":[{"I":0,"D":"Relay0"},{"I":1,"D":"Sensors"}],"sen":[{"I":112,"T":"S","D":"Switch","R":"0/1","L":0},{"I":118,"T":"S","D":"Input","R":"0/1/2","L":1}]}
> 12:18:18.204728 IP 192.168.0.81.5683 > 192.168.0.50.5683: UDP, length 179
> E..........w...Q...2.3.3....PE.
> ....SHSW-1#xxxxxx#1.{"blk":[{"I":0,"D":"Relay0"},{"I":1,"D":"Sensors"}],"sen":[{"I":112,"T":"S","D":"Switch","R":"0/1","L":0},{"I":118,"T":"S","D":"Input","R":"0/1/2","L":1}]}

Did you give it enought time ?
From your dump seems you miss the "cit.s" from Shelly to HASS.

It may indeed be a network problem. Mine was solved changing router (From provider's one to Fritzbox 7590).

Simone

**Comment by emnik** [comment] 2020-02-28 19:33
Yes I gave it quite a time. You see... I did exactly the opposite from you!
I had the provider's router which worked with coap but I changed it for a TP-LINK Archer C3150 which has many more capabilities. The reason was that I had many WiFi devices that the provider's router was struggling and I had disconnections, poor speed when streaming or downloading etc. All these are solved now but CoAP is not working anymore ... and I come to  believe I cannot do anything for it except maybe to use an openWRT firmware for the modem. Though I dont want to as I've just bought the router :-(

**Comment by InToSSH** [comment] 2020-03-02 14:12
@emnik I have ZyXEL Armor Z2, with OpenWRT FW on it and I have the same problem. I managed to make CoAP discovery work by adding host_ip, beacuse my HA is running in Docker on Debian VM which has multiple interfaces (LAN, IoT and NoT). I am not sure how CoAP works, but since it has direct access to the subnet where Shellies are, isn't it supposed to communicate directly with the devices, or use broadcast which would be picked up by the shelly? If it was in a different subnet which would require to use default gateway to route to the destination subnet, I would get it, that router would have to be set up correctly, but in this case, in theory no router would be needed at all, yet the problem is still there. Only thing on it's way to reaching those devices in my Unifi AC Pro and Unifi switch, perhaps it might be filtering something? I can try tcpdump or tshark aswell.

**Comment by chemelli74** [comment] 2020-03-03 12:45
> I am not sure how CoAP works, but since it has direct access to the subnet where Shellies are, isn't it supposed to communicate directly with the devices, or use broadcast which would be picked up by the shelly? If it was in a different subnet which would require to use default gateway to route to the destination subnet, I would get it, that router would have to be set up correctly, but in this case, in theory no router would be needed at all, yet the problem is still there. [...] Only thing on it's way to reaching those devices in my Unifi AC Pro and Unifi switch, perhaps it might be filtering something?

You got the point, it's not the router the issue, but the AP.
A lot of people usually have the device provided by the internet provider and this is a single device that is both a router and a AP.
So they write router but they mean router+AP ;-)

Simone

**Comment by InToSSH** [comment] 2020-03-03 21:02
@chemelli74 yea, I realized that shortly after I posted that message, haha. Well that would mean that there is also some problem with my Unifi APs, I will take a look, but I thought they aren't supposed to  interrupt any traffic, they should pass it right through.

**Comment by dodg3r** [comment] 2020-03-08 15:46
Hi.

Updated to 0.1.7 beta1 on my dev installation and got the same delays. Coap is working.

Should I start a new thread on this or what to do :)

**Comment by chemelli74** [comment] 2020-03-08 22:15
> Hi.
> 
> Updated to 0.1.7 beta1 on my dev installation and got the same delays. Coap is working.
> 
> Should I start a new thread on this or what to do :)

Issue is network related and not on ShellyForHASS code, as far as we know.

Simone

**Comment by dodg3r** [comment] 2020-03-09 06:21
> > Hi.
> > Updated to 0.1.7 beta1 on my dev installation and got the same delays. Coap is working.
> > Should I start a new thread on this or what to do :)
> 
> Issue is network related and not on ShellyForHASS code, as far as we know.
> 
> Simone

Ok. I thought it was strange that this happened for me when I updated to 0.1.7beta1. 
I reverted back to 0.1.6 and now it works again.

**Comment by dodg3r** [comment] 2020-03-14 09:11
> > > Hi.
> > > Updated to 0.1.7 beta1 on my dev installation and got the same delays. Coap is working.
> > > Should I start a new thread on this or what to do :)
> > 
> > 
> > Issue is network related and not on ShellyForHASS code, as far as we know.
> > Simone
> 
> Ok. I thought it was strange that this happened for me when I updated to 0.1.7beta1.
> I reverted back to 0.1.6 and now it works again.
> 
> Look at this video.
> https://1drv.ms/v/s!AgZRSIF72Mnv6kE-TjgNaR3fiJ7E



> > Hi.
> > Updated to 0.1.7 beta1 on my dev installation and got the same delays. Coap is working.
> > Should I start a new thread on this or what to do :)
> 
> Issue is network related and not on ShellyForHASS code, as far as we know.
> 
> Simone

In my case the delays is gone in beta2

**Comment by chemelli74** [comment] 2020-03-14 09:25
I'm going to close this issue.

If someone **with CoAP working** will have the same problem in future a new issue needs to be opened.

Simone

**Closed by chemelli74** 2020-03-14 09:25 UTC
Labels: enhancement, question
