### ISSUE TITLE
ShellyEM consumption attribute is not present

### ISSUE THREAD

**Issue by ericfesta** [StyraHem/ShellyForHASS#125] opened 2019-12-19 18:35 UTC
I got my Shelly1PM and ShellyEM discovered by mDns; I can read the Shelly1PM consumption but the ShellyEM consumption attribute value remains unknown.

I already tried to reboot multiple times with no luck.
Any help would be much appreciated!

State attributes of the ShellyEM:
```
ip_address: 192.168.1.138
shelly_type: Shelly EM
shelly_id: B9E66B-1
discovery: mDns
ssid: fHome2
rssi: -68
uptime: 104491
has_firmware_update: false
latest_fw_version: 20191216-090635/v1.5.7@c30657ba
firmware_version: 20191216-090635/v1.5.7@c30657ba
cloud_enabled: false
cloud_connected: false
mqtt_connected: false
cloud_status: disabled
unit_of_measurement: W
friendly_name: 'Shelly EM [B9E66B-1]'
```

configuration.yaml has:
```
shelly:
  discovery: true
  additional_information: true
  sensors:
    - all
```

**Comment by pilot1981** [comment] 2019-12-30 17:27
Hi,
@ericfesta I have same issue: how you have solved it?
@StyraHem this is a bug?

**Comment by Boogs77** [comment] 2019-12-31 00:09
Hi. I got same issue with Shelly Em.

**Comment by hakana** [comment] 2020-01-14 22:52
I tested in latest release 0.1.6.b4, please test if it working for you too.

**Comment by Malvaggio** [comment] 2020-01-19 21:02
You need to change 

STATUS_RESPONSE_METERS = 'meters'  to  STATUS_RESPONSE_METERS = 'emeters'
on line 21 of pyShelly/pyShelly/const.py

**Comment by pilot1981** [comment] 2020-01-20 07:30
@Malvaggio you wrote to developer @StyraHem @hakana ?

**Comment by Malvaggio** [comment] 2020-01-20 15:25
@pilot1981 Yes i sent a PM yesterday

**Comment by ericfesta** [comment] 2020-01-21 00:35
> I tested in latest release 0.1.6.b4, please test if it working for you too.

@hakana I tested in release 0.1.6.b6 but still not working.

**Comment by maverick1975** [comment] 2020-01-25 14:52
is possible on shelly em read voltage and current ? i have problem whit voltage at my home and i think monitor value with shelly em but only on shelly app i read voltage value 
tank's

**Comment by chemelli74** [comment] 2020-02-19 22:50
> You need to change
> 
> STATUS_RESPONSE_METERS = 'meters' to STATUS_RESPONSE_METERS = 'emeters'
> on line 21 of pyShelly/pyShelly/const.py

@hakana, cn you please review this comment about code typo to fx the issue ?

Simone

**Comment by maverick1975** [comment] 2020-02-20 07:29
@chemelli74  I don't find const.py file ... in custom_components > shelly file not present

tank's

**Comment by chemelli74** [comment] 2020-02-20 08:12
> @chemelli74 I don't find const.py file ... in custom_components > shelly file not present
> 
> tank's

Which version of this plugin are you running ? File "const.py" is there on latest 0.1.6

Simone

**Comment by hakana** [comment] 2020-02-20 09:29
This is solved in the latest stable release (0.1.6). 

There is a bug in 0.1.6 that gives the wrong value of total_effect for Shelly EM, will be fixed in the next release.

**Comment by maverick1975** [comment] 2020-02-20 11:34
i update 0.1.6 but in const.py not present in line 21 "STATUS_RESPONSE_METERS"

**Comment by chemelli74** [comment] 2020-02-20 11:56
> i update 0.1.6 but in const.py not present in line 21 "STATUS_RESPONSE_METERS"

As per author comment, please try without changing the code.

Simone

**Comment by maverick1975** [comment] 2020-02-20 18:50
Nothing 😅 voltage not present!!

**Comment by hakana** [comment] 2020-02-20 21:51
Sorry, my fault. It will be included in next release 0.1.7, beta 1 will soon be available for test.

**Comment by chemelli74** [comment] 2020-03-05 09:33
Please update to 0.1.7b1 and recheck.

Simone

**Comment by chemelli74** [comment] 2020-03-14 08:48
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-03-26 09:35
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-03-26 09:35 UTC
Labels: enhancement, fixed, waiting for feedback
