### ISSUE TITLE
[BUG] entity_id changed only for switch, not for sensors / attributes

### ISSUE THREAD

**Issue by matejzero** [StyraHem/ShellyForHASS#343] opened 2020-07-03 09:23 UTC
## Environment

- ShellyForHASS release with the issue: 0.1.8
- Last working ShellyForHASS release (if known): /
- Home Assistant Core release with the issue: 0.111.4
- Operating environment (Home Assistant/Supervised/Docker/venv): HassOS

## Describe the bug
I added the following overwrite to my YAML file:
```yaml
shelly:
  discovery: true
  devices:
    - id: 259AAA
      name: Diningroom table light
      light_switch: true
      entity_id: diningroom_table_light
```

I was expecting to get all entities_id from this switch renamed like

- light.diningroom_table_light
- sensor.shelly_diningroom_table_light_consumption
- sensor.shelly_diningroom_table_light_rssi

Instead I got 
- light.diningroom_table_light
- sensor.shelly_shsw_1_ 259aaa_consumption
- sensor.shelly_shsw_1_ 259aaa_rssi
- sensor.shelly_shsw_1_ 259aaa

So only light is renamed, but the rest keep the original name.

## Steps to Reproduce
I added a new shelly, added overwrite in YAML file and restarted HA.

## Expected behavior
I expect it to rename all entity_ids for a switch/sensor.

## Traceback/Error logs
Not sure if this is related to this issue, but this are the only warnings / errors I see regarding shelly in HA logs

```txt
2020-07-03 11:04:55 WARNING (MainThread) [homeassistant.components.light] Light is deprecated, modify ShellyLightRelay to extend LightEntity
2020-07-03 11:04:55 WARNING (MainThread) [homeassistant.components.light] Light is deprecated, modify ShellyDimmer to extend LightEntity
2020-07-03 11:04:55 WARNING (MainThread) [homeassistant.components.light] Light is deprecated, modify ShellyRGB to extend LightEntity
2020-07-03 11:04:55 WARNING (MainThread) [homeassistant.components.switch] SwitchDevice is deprecated, modify ShellySwitch to extend SwitchEntity
2020-07-03 11:04:55 WARNING (MainThread) [homeassistant.components.switch] SwitchDevice is deprecated, modify ShellyFirmwareUpdate to extend SwitchEntity
2020-07-03 11:04:55 WARNING (MainThread) [homeassistant.components.binary_sensor] BinarySensorDevice is deprecated, modify ShellySwitch to extend BinarySensorEntity
2020-07-03 11:04:55 WARNING (MainThread) [homeassistant.components.binary_sensor] BinarySensorDevice is deprecated, modify ShellyBinarySensor to extend BinarySensorEntity
2020-07-03 11:04:55 WARNING (MainThread) [homeassistant.components.binary_sensor] BinarySensorDevice is deprecated, modify ShellyBinaryInfoSensor to extend BinarySensorEntity
2020-07-03 11:04:57 ERROR (MainThread) [homeassistant.components.sensor] Entity id already exists - ignoring: sensor.shelly_shrgbw2_f43d29_1_current_consumption. Platform shelly does not generate unique IDs
2020-07-03 11:04:57 ERROR (MainThread) [homeassistant.components.sensor] Entity id already exists - ignoring: sensor.shelly_shrgbw2_f43d29_1_current_consumption. Platform shelly does not generate unique IDs
```

## Additional context

Similar, if not exact, bug was already opened about a year ago and should be fixed, but it doesn't seem to be: https://github.com/StyraHem/ShellyForHASS/issues/67

**Comment by chemelli74** [comment] 2020-07-08 22:35
Please try version 0.1.9b2 and report back.

Simone

**Comment by matejzero** [comment] 2020-07-09 20:42
Doesn't work with b2 either. I must say, I don't have Shelly cloud configured if that plays any role, so local only.

And I only installed b2 version and restarted HA, no other changes.

**Comment by chemelli74** [comment] 2020-07-27 07:41
I bet using 0.1.9 log is clean, but the rename is missing ? Right ?

Simone

**Comment by chemelli74** [comment] 2020-08-01 12:42
Hi all, just to inform that after 3 weeks of inactivity on thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-08-28 21:12
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-08-28 21:12 UTC
Labels: support, waiting for feedback
