### ISSUE TITLE
Round power consumption to one decimal place

### ISSUE THREAD

**Issue by janbernhardt** [StyraHem/ShellyForHASS#166] opened 2020-01-25 06:17 UTC
Hi,

I love your integration. Works perfectly!
I would like to ask if you could round the power consumption value (used as an attribute and as a sensor value) to have only one decimal place. It looks strange, when sometimes the Watt value has 5 decimal digits that are not so much meaningful anyway.

Many thanks!

**Comment by chemelli74** [comment] 2020-01-25 08:31
Hi,

just configure the following parameter:

`power_decimals`
 
Round power sensor values to the given number of decimals

Simone

**Comment by chemelli74** [comment] 2020-01-30 15:26
@janbernhardt, any feedback ? If working can you close the issue please ?

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-02-09 19:01
Hi all, 

just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-02-19 22:45
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-02-19 22:45 UTC
Labels: support
