### ISSUE TITLE
power_decimals not possible 0?

### ISSUE THREAD

**Issue by Klagio** [StyraHem/ShellyForHASS#95] opened 2019-11-12 14:09 UTC
I put power_decimals: 0

and I receive an error, I wish to have a Watt number without decimals, possible?

**Comment by chemelli74** [comment] 2020-01-22 08:28
@Klagio, please retest with 0.1.6b7.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-01-30 15:02
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-02-12 22:23
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-02-12 22:23 UTC
Labels: fixed
