### ISSUE TITLE
Flood Sensor doesn't change state

### ISSUE THREAD

**Issue by CiquattroFPV** [StyraHem/ShellyForHASS#81] opened 2019-10-01 19:35 UTC
I have a flood sensor and I noticed that the Flood Sensor doesn't change the state when a flood is detected/trigger .. it remain false all the time.

**Comment by CiquattroFPV** [comment] 2019-11-05 17:19
Any update on this? Do you need more information? How I can help for resolve the issue?

**Comment by CiquattroFPV** [comment] 2019-11-05 17:19
Any update on this? Do you need more information? How I can help for resolve the issue?

**Comment by chemelli74** [comment] 2020-01-21 10:42
@CiquattroFPV , can you please retest with 0.1.6b6 ? Please update firmware to latest version as well.

Thank you,

Simone

**Comment by CiquattroFPV** [comment] 2020-01-28 10:05
I have tested it but it doesn't change the state on Home assistant binary_sensor when an event is triggered.

**Comment by chemelli74** [comment] 2020-01-30 15:00
Please enable debug log and post it.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-02-10 14:36
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment] 2020-02-20 07:48
No update for 21 days, closing

Simone

**Closed by chemelli74** 2020-02-20 07:48 UTC
Labels: waiting for feedback
